// Levis 插件契约。
//
// 插件是独立的可执行程序，与主程序通过本文件定义的 gRPC 服务通信。
// 主程序始终是客户端，插件是服务端 —— 插件若要读写 Levis 的数据，
// 走 HTTP 回调 /api/plugin/v1，不在本契约内。
//
// 兼容性约定：字段只增不改，废弃字段用 reserved 占位，绝不复用编号。
// 插件与主程序的版本可能不一致，改动必须让旧插件仍能工作。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Plugin_Describe_FullMethodName              = "/levis.plugin.v1.Plugin/Describe"
	Plugin_Configure_FullMethodName             = "/levis.plugin.v1.Plugin/Configure"
	Plugin_Health_FullMethodName                = "/levis.plugin.v1.Plugin/Health"
	Plugin_Shutdown_FullMethodName              = "/levis.plugin.v1.Plugin/Shutdown"
	Plugin_SendMail_FullMethodName              = "/levis.plugin.v1.Plugin/SendMail"
	Plugin_CreatePayment_FullMethodName         = "/levis.plugin.v1.Plugin/CreatePayment"
	Plugin_QueryPayment_FullMethodName          = "/levis.plugin.v1.Plugin/QueryPayment"
	Plugin_VerifyPaymentCallback_FullMethodName = "/levis.plugin.v1.Plugin/VerifyPaymentCallback"
)

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Plugin 是每个插件都必须实现的服务。
//
// 生命周期方法（Describe/Configure/Health/Shutdown）是必须实现的；能力方法
// 按 Manifest 里声明的 capabilities 实现，未声明的直接返回 UNIMPLEMENTED，
// 主程序不会去调。
type PluginClient interface {
	// Describe 返回插件的身份与能力。主程序在握手后立刻调用。
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*Manifest, error)
	// Configure 下发管理员在后台填写的配置。
	//
	// 每次配置变更后都会重新调用，插件应当能够重复接收 —— 比如把 SMTP
	// 连接池按新参数重建，而不是只在第一次生效。
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureReply, error)
	// Health 用于存活探测，主程序按固定间隔调用。
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error)
	// Shutdown 通知插件即将退出，插件应当收尾并尽快返回。
	//
	// 返回后主程序仍会等待进程自行退出，超时才发信号。
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error)
	// SendMail 发送一封邮件。需声明 CAPABILITY_SEND_MAIL。
	SendMail(ctx context.Context, in *SendMailRequest, opts ...grpc.CallOption) (*SendMailReply, error)
	// CreatePayment 创建一笔支付，返回可供用户跳转的地址。
	// 需声明 CAPABILITY_CREATE_PAYMENT。
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentReply, error)
	// QueryPayment 查询一笔支付的当前状态，用于用户回到站点后主动核对，
	// 不依赖渠道回调是否已经到达。需声明 CAPABILITY_CREATE_PAYMENT。
	QueryPayment(ctx context.Context, in *QueryPaymentRequest, opts ...grpc.CallOption) (*QueryPaymentReply, error)
	// VerifyPaymentCallback 验证并归一化支付渠道的异步通知。
	// 主程序只把渠道原始字段交给插件，不信任其中的用户、金额或支付状态；
	// 插件验签后返回商户单号与实收金额，再由主程序匹配本地支付意图。
	// 需声明 CAPABILITY_CREATE_PAYMENT。
	VerifyPaymentCallback(ctx context.Context, in *VerifyPaymentCallbackRequest, opts ...grpc.CallOption) (*VerifyPaymentCallbackReply, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*Manifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Manifest)
	err := c.cc.Invoke(ctx, Plugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureReply)
	err := c.cc.Invoke(ctx, Plugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, Plugin_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownReply)
	err := c.cc.Invoke(ctx, Plugin_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) SendMail(ctx context.Context, in *SendMailRequest, opts ...grpc.CallOption) (*SendMailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMailReply)
	err := c.cc.Invoke(ctx, Plugin_SendMail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentReply)
	err := c.cc.Invoke(ctx, Plugin_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) QueryPayment(ctx context.Context, in *QueryPaymentRequest, opts ...grpc.CallOption) (*QueryPaymentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPaymentReply)
	err := c.cc.Invoke(ctx, Plugin_QueryPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) VerifyPaymentCallback(ctx context.Context, in *VerifyPaymentCallbackRequest, opts ...grpc.CallOption) (*VerifyPaymentCallbackReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPaymentCallbackReply)
	err := c.cc.Invoke(ctx, Plugin_VerifyPaymentCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility.
//
// Plugin 是每个插件都必须实现的服务。
//
// 生命周期方法（Describe/Configure/Health/Shutdown）是必须实现的；能力方法
// 按 Manifest 里声明的 capabilities 实现，未声明的直接返回 UNIMPLEMENTED，
// 主程序不会去调。
type PluginServer interface {
	// Describe 返回插件的身份与能力。主程序在握手后立刻调用。
	Describe(context.Context, *DescribeRequest) (*Manifest, error)
	// Configure 下发管理员在后台填写的配置。
	//
	// 每次配置变更后都会重新调用，插件应当能够重复接收 —— 比如把 SMTP
	// 连接池按新参数重建，而不是只在第一次生效。
	Configure(context.Context, *ConfigureRequest) (*ConfigureReply, error)
	// Health 用于存活探测，主程序按固定间隔调用。
	Health(context.Context, *HealthRequest) (*HealthReply, error)
	// Shutdown 通知插件即将退出，插件应当收尾并尽快返回。
	//
	// 返回后主程序仍会等待进程自行退出，超时才发信号。
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownReply, error)
	// SendMail 发送一封邮件。需声明 CAPABILITY_SEND_MAIL。
	SendMail(context.Context, *SendMailRequest) (*SendMailReply, error)
	// CreatePayment 创建一笔支付，返回可供用户跳转的地址。
	// 需声明 CAPABILITY_CREATE_PAYMENT。
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentReply, error)
	// QueryPayment 查询一笔支付的当前状态，用于用户回到站点后主动核对，
	// 不依赖渠道回调是否已经到达。需声明 CAPABILITY_CREATE_PAYMENT。
	QueryPayment(context.Context, *QueryPaymentRequest) (*QueryPaymentReply, error)
	// VerifyPaymentCallback 验证并归一化支付渠道的异步通知。
	// 主程序只把渠道原始字段交给插件，不信任其中的用户、金额或支付状态；
	// 插件验签后返回商户单号与实收金额，再由主程序匹配本地支付意图。
	// 需声明 CAPABILITY_CREATE_PAYMENT。
	VerifyPaymentCallback(context.Context, *VerifyPaymentCallbackRequest) (*VerifyPaymentCallbackReply, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServer struct{}

func (UnimplementedPluginServer) Describe(context.Context, *DescribeRequest) (*Manifest, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedPluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedPluginServer) Health(context.Context, *HealthRequest) (*HealthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPluginServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPluginServer) SendMail(context.Context, *SendMailRequest) (*SendMailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMail not implemented")
}
func (UnimplementedPluginServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPluginServer) QueryPayment(context.Context, *QueryPaymentRequest) (*QueryPaymentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryPayment not implemented")
}
func (UnimplementedPluginServer) VerifyPaymentCallback(context.Context, *VerifyPaymentCallbackRequest) (*VerifyPaymentCallbackReply, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPaymentCallback not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}
func (UnimplementedPluginServer) testEmbeddedByValue()                {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	// If the following call panics, it indicates UnimplementedPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).SendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_SendMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).SendMail(ctx, req.(*SendMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_QueryPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).QueryPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_QueryPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).QueryPayment(ctx, req.(*QueryPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_VerifyPaymentCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPaymentCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).VerifyPaymentCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_VerifyPaymentCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).VerifyPaymentCallback(ctx, req.(*VerifyPaymentCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "levis.plugin.v1.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Plugin_Describe_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Plugin_Configure_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Plugin_Health_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Plugin_Shutdown_Handler,
		},
		{
			MethodName: "SendMail",
			Handler:    _Plugin_SendMail_Handler,
		},
		{
			MethodName: "CreatePayment",
			Handler:    _Plugin_CreatePayment_Handler,
		},
		{
			MethodName: "QueryPayment",
			Handler:    _Plugin_QueryPayment_Handler,
		},
		{
			MethodName: "VerifyPaymentCallback",
			Handler:    _Plugin_VerifyPaymentCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
