// Command gen-proto-compat derives internal source compatibility aliases from
// the public protoc output. It intentionally emits no descriptor registration.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
)

func main() {
	for _, name := range []string{"plugin.pb.go", "plugin_grpc.pb.go"} {
		f, err := parser.ParseFile(token.NewFileSet(), filepath.Join("pkg/plugin/proto", name), nil, 0)
		must(err)
		var b bytes.Buffer
		fmt.Fprintln(&b, "// Code generated by scripts/gen-proto-compat; DO NOT EDIT.\npackage proto\n\nimport public \"github.com/SakuraOpenSource/levis/pkg/plugin/proto\"")
		for _, d := range f.Decls {
			switch d := d.(type) {
			case *ast.GenDecl:
				for _, spec := range d.Specs {
					switch spec := spec.(type) {
					case *ast.TypeSpec:
						if ast.IsExported(spec.Name.Name) {
							fmt.Fprintf(&b, "type %s = public.%s\n", spec.Name, spec.Name)
						}
					case *ast.ValueSpec:
						for _, n := range spec.Names {
							if ast.IsExported(n.Name) {
								kind := "var"
								if d.Tok == token.CONST {
									kind = "const"
								}
								fmt.Fprintf(&b, "%s %s = public.%s\n", kind, n, n)
							}
						}
					}
				}
			case *ast.FuncDecl:
				if d.Recv == nil && ast.IsExported(d.Name.Name) {
					fmt.Fprintf(&b, "var %s = public.%s\n", d.Name, d.Name)
				}
			}
		}
		code, err := format.Source(b.Bytes())
		must(err)
		must(os.WriteFile(filepath.Join("internal/plugin/proto", name), code, 0644))
	}
	source, err := os.ReadFile("pkg/plugin/proto/plugin.proto")
	must(err)
	must(os.WriteFile("internal/plugin/proto/plugin.proto", source, 0644))
}
func must(err error) {
	if err != nil {
		panic(err)
	}
}
