// Levis 插件契约。
//
// 插件是独立的可执行程序，与主程序通过本文件定义的 gRPC 服务通信。
// 主程序始终是客户端，插件是服务端 —— 插件若要读写 Levis 的数据，
// 走 HTTP 回调 /api/plugin/v1，不在本契约内。
//
// 兼容性约定：字段只增不改，废弃字段用 reserved 占位，绝不复用编号。
// 插件与主程序的版本可能不一致，改动必须让旧插件仍能工作。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Capability 是插件声明的能力。
//
// 每一项对应一组 RPC，主程序据此决定哪些 hook 可以派发给这个插件。
type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED    Capability = 0
	Capability_CAPABILITY_SEND_MAIL      Capability = 1
	Capability_CAPABILITY_CREATE_PAYMENT Capability = 2
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "CAPABILITY_SEND_MAIL",
		2: "CAPABILITY_CREATE_PAYMENT",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED":    0,
		"CAPABILITY_SEND_MAIL":      1,
		"CAPABILITY_CREATE_PAYMENT": 2,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// FieldType 是配置项的输入类型，决定后台表单的渲染方式。
type FieldType int32

const (
	FieldType_FIELD_TYPE_UNSPECIFIED FieldType = 0
	FieldType_FIELD_TYPE_TEXT        FieldType = 1
	FieldType_FIELD_TYPE_NUMBER      FieldType = 2
	FieldType_FIELD_TYPE_BOOL        FieldType = 3
	FieldType_FIELD_TYPE_SELECT      FieldType = 4
	// FIELD_TYPE_TEXTAREA 用于私钥、证书这类多行内容。
	FieldType_FIELD_TYPE_TEXTAREA FieldType = 5
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "FIELD_TYPE_TEXT",
		2: "FIELD_TYPE_NUMBER",
		3: "FIELD_TYPE_BOOL",
		4: "FIELD_TYPE_SELECT",
		5: "FIELD_TYPE_TEXTAREA",
	}
	FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"FIELD_TYPE_TEXT":        1,
		"FIELD_TYPE_NUMBER":      2,
		"FIELD_TYPE_BOOL":        3,
		"FIELD_TYPE_SELECT":      4,
		"FIELD_TYPE_TEXTAREA":    5,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

// PaymentState 是一笔支付在渠道侧的状态。
type PaymentState int32

const (
	PaymentState_PAYMENT_STATE_UNSPECIFIED PaymentState = 0
	PaymentState_PAYMENT_STATE_PENDING     PaymentState = 1
	PaymentState_PAYMENT_STATE_PAID        PaymentState = 2
	PaymentState_PAYMENT_STATE_FAILED      PaymentState = 3
	PaymentState_PAYMENT_STATE_CANCELLED   PaymentState = 4
)

// Enum value maps for PaymentState.
var (
	PaymentState_name = map[int32]string{
		0: "PAYMENT_STATE_UNSPECIFIED",
		1: "PAYMENT_STATE_PENDING",
		2: "PAYMENT_STATE_PAID",
		3: "PAYMENT_STATE_FAILED",
		4: "PAYMENT_STATE_CANCELLED",
	}
	PaymentState_value = map[string]int32{
		"PAYMENT_STATE_UNSPECIFIED": 0,
		"PAYMENT_STATE_PENDING":     1,
		"PAYMENT_STATE_PAID":        2,
		"PAYMENT_STATE_FAILED":      3,
		"PAYMENT_STATE_CANCELLED":   4,
	}
)

func (x PaymentState) Enum() *PaymentState {
	p := new(PaymentState)
	*p = x
	return p
}

func (x PaymentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentState) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[2].Descriptor()
}

func (PaymentState) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[2]
}

func (x PaymentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentState.Descriptor instead.
func (PaymentState) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

// ConfigField 描述一个配置项。插件用它告诉后台该渲染什么表单。
type ConfigField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key 是配置项标识，主程序按 (插件 ID, key) 落库。
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// label 是表单上显示的名称。
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// hint 是字段下方的补充说明，可为空。
	Hint     string    `protobuf:"bytes,3,opt,name=hint,proto3" json:"hint,omitempty"`
	Type     FieldType `protobuf:"varint,4,opt,name=type,proto3,enum=levis.plugin.v1.FieldType" json:"type,omitempty"`
	Required bool      `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	// secret 为 true 时，接口永不回传该项的值，后台渲染为密码框。
	// SMTP 密码、渠道私钥都应当置为 true。
	Secret bool `protobuf:"varint,6,opt,name=secret,proto3" json:"secret,omitempty"`
	// default_value 在管理员未填写时作为初始值展示。
	// secret 字段不应给默认值。
	DefaultValue string `protobuf:"bytes,7,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// options 仅在 FIELD_TYPE_SELECT 时有意义。
	Options       []*SelectOption `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigField) Reset() {
	*x = ConfigField{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigField) ProtoMessage() {}

func (x *ConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigField.ProtoReflect.Descriptor instead.
func (*ConfigField) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ConfigField) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *ConfigField) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *ConfigField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigField) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *ConfigField) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ConfigField) GetOptions() []*SelectOption {
	if x != nil {
		return x.Options
	}
	return nil
}

// SelectOption 是下拉框的一个选项。
type SelectOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectOption) Reset() {
	*x = SelectOption{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectOption) ProtoMessage() {}

func (x *SelectOption) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectOption.ProtoReflect.Descriptor instead.
func (*SelectOption) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *SelectOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SelectOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

// Manifest 是插件的自我描述。
type Manifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 是展示名，如「SMTP 邮件发送」。
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version 是插件自己的版本号，仅用于展示与排错。
	Version     string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// author 可为空。
	Author       string         `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Capabilities []Capability   `protobuf:"varint,5,rep,packed,name=capabilities,proto3,enum=levis.plugin.v1.Capability" json:"capabilities,omitempty"`
	Config       []*ConfigField `protobuf:"bytes,6,rep,name=config,proto3" json:"config,omitempty"`
	// required_scopes 是插件回调 /api/plugin/v1 所需的权限位，
	// 取值见 model.PluginScope*。主程序据此签发 Key，管理员可见。
	RequiredScopes []string `protobuf:"bytes,7,rep,name=required_scopes,json=requiredScopes,proto3" json:"required_scopes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manifest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manifest) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Manifest) GetConfig() []*ConfigField {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Manifest) GetRequiredScopes() []string {
	if x != nil {
		return x.RequiredScopes
	}
	return nil
}

type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values 是配置项的当前值，键为 ConfigField.key。
	//
	// 一律用字符串传递，由插件按自己声明的 type 解析：数字与布尔在这里
	// 不值得为其各开一个字段，插件本来就知道自己要什么类型。
	Values        map[string]string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureRequest) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ConfigureReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error 非空表示配置不可用（比如 SMTP 连不上），主程序会把它显示在
	// 后台并把插件标为异常。不要用 gRPC 错误返回这类信息 —— 配置错误是
	// 预期内的结果，不是调用失败。
	Error         string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureReply) Reset() {
	*x = ConfigureReply{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureReply) ProtoMessage() {}

func (x *ConfigureReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureReply.ProtoReflect.Descriptor instead.
func (*ConfigureReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigureReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

type HealthReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// message 在 ok 为 false 时说明原因。
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReply) Reset() {
	*x = HealthReply{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReply) ProtoMessage() {}

func (x *HealthReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReply.ProtoReflect.Descriptor instead.
func (*HealthReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *HealthReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

type ShutdownReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownReply) Reset() {
	*x = ShutdownReply{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownReply) ProtoMessage() {}

func (x *ShutdownReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownReply.ProtoReflect.Descriptor instead.
func (*ShutdownReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

// Mailbox 是一个收件人。
type Mailbox struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// name 可为空，为空时只用地址。
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mailbox) Reset() {
	*x = Mailbox{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mailbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mailbox) ProtoMessage() {}

func (x *Mailbox) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mailbox.ProtoReflect.Descriptor instead.
func (*Mailbox) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *Mailbox) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Mailbox) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SendMailRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	To      []*Mailbox             `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Subject string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// text_body 是纯文本正文，始终提供。
	TextBody string `protobuf:"bytes,3,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	// html_body 可为空；插件应在为空时只发纯文本。
	HtmlBody      string `protobuf:"bytes,4,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailRequest) Reset() {
	*x = SendMailRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailRequest) ProtoMessage() {}

func (x *SendMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailRequest.ProtoReflect.Descriptor instead.
func (*SendMailRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *SendMailRequest) GetTo() []*Mailbox {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendMailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendMailRequest) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *SendMailRequest) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

type SendMailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailReply) Reset() {
	*x = SendMailReply{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailReply) ProtoMessage() {}

func (x *SendMailReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailReply.ProtoReflect.Descriptor instead.
func (*SendMailReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

type CreatePaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// external_id 由主程序生成，插件必须在回调 /api/plugin/v1/wallet/credit
	// 时原样带回 —— 它是加钱幂等的依据，渠道重复回调时靠它去重。
	ExternalId string `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// amount_cents 是金额，整数分。全系统不使用浮点表示金额。
	AmountCents int64 `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	// currency 是 ISO 4217 代码，如 CNY。
	Currency string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	// subject 是给用户看的付款说明。
	Subject string `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	UserId  uint64 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// return_url 是用户付完款后应当跳回的站内地址。
	ReturnUrl     string `protobuf:"bytes,6,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePaymentRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreatePaymentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePaymentRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

type CreatePaymentReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pay_url 是让用户跳转过去完成支付的地址。
	PayUrl string `protobuf:"bytes,1,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	// gateway_ref 是渠道侧的单号，落库备查，可为空。
	GatewayRef string `protobuf:"bytes,2,opt,name=gateway_ref,json=gatewayRef,proto3" json:"gateway_ref,omitempty"`
	// error 非空表示创建失败且原因可以展示给用户（如「金额低于渠道下限」）。
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReply) Reset() {
	*x = CreatePaymentReply{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReply) ProtoMessage() {}

func (x *CreatePaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReply.ProtoReflect.Descriptor instead.
func (*CreatePaymentReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePaymentReply) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *CreatePaymentReply) GetGatewayRef() string {
	if x != nil {
		return x.GatewayRef
	}
	return ""
}

func (x *CreatePaymentReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QueryPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	GatewayRef    string                 `protobuf:"bytes,2,opt,name=gateway_ref,json=gatewayRef,proto3" json:"gateway_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentRequest) Reset() {
	*x = QueryPaymentRequest{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentRequest) ProtoMessage() {}

func (x *QueryPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentRequest.ProtoReflect.Descriptor instead.
func (*QueryPaymentRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *QueryPaymentRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *QueryPaymentRequest) GetGatewayRef() string {
	if x != nil {
		return x.GatewayRef
	}
	return ""
}

type QueryPaymentReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State PaymentState           `protobuf:"varint,1,opt,name=state,proto3,enum=levis.plugin.v1.PaymentState" json:"state,omitempty"`
	// paid_amount_cents 是渠道实际收到的金额，整数分。
	//
	// 主程序会核对它与请求金额是否一致：不一致时不入账并记录告警，
	// 避免「付一分钱开通一年」这类少付攻击。
	PaidAmountCents int64  `protobuf:"varint,2,opt,name=paid_amount_cents,json=paidAmountCents,proto3" json:"paid_amount_cents,omitempty"`
	Message         string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryPaymentReply) Reset() {
	*x = QueryPaymentReply{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentReply) ProtoMessage() {}

func (x *QueryPaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentReply.ProtoReflect.Descriptor instead.
func (*QueryPaymentReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *QueryPaymentReply) GetState() PaymentState {
	if x != nil {
		return x.State
	}
	return PaymentState_PAYMENT_STATE_UNSPECIFIED
}

func (x *QueryPaymentReply) GetPaidAmountCents() int64 {
	if x != nil {
		return x.PaidAmountCents
	}
	return 0
}

func (x *QueryPaymentReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyPaymentCallbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// raw 是渠道通知的原始表单或 JSON 字段，主程序不解释其含义。
	Raw           map[string]string `protobuf:"bytes,1,rep,name=raw,proto3" json:"raw,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPaymentCallbackRequest) Reset() {
	*x = VerifyPaymentCallbackRequest{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentCallbackRequest) ProtoMessage() {}

func (x *VerifyPaymentCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentCallbackRequest.ProtoReflect.Descriptor instead.
func (*VerifyPaymentCallbackRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *VerifyPaymentCallbackRequest) GetRaw() map[string]string {
	if x != nil {
		return x.Raw
	}
	return nil
}

type VerifyPaymentCallbackReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// external_id 必须是 CreatePaymentRequest 下发的商户单号。
	ExternalId string `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// gateway_ref 是渠道侧流水号，可为空。
	GatewayRef      string       `protobuf:"bytes,2,opt,name=gateway_ref,json=gatewayRef,proto3" json:"gateway_ref,omitempty"`
	State           PaymentState `protobuf:"varint,3,opt,name=state,proto3,enum=levis.plugin.v1.PaymentState" json:"state,omitempty"`
	PaidAmountCents int64        `protobuf:"varint,4,opt,name=paid_amount_cents,json=paidAmountCents,proto3" json:"paid_amount_cents,omitempty"`
	// currency 可为空；非空时主程序必须核对为 CNY。
	Currency      string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Message       string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPaymentCallbackReply) Reset() {
	*x = VerifyPaymentCallbackReply{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentCallbackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentCallbackReply) ProtoMessage() {}

func (x *VerifyPaymentCallbackReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentCallbackReply.ProtoReflect.Descriptor instead.
func (*VerifyPaymentCallbackReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *VerifyPaymentCallbackReply) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *VerifyPaymentCallbackReply) GetGatewayRef() string {
	if x != nil {
		return x.GatewayRef
	}
	return ""
}

func (x *VerifyPaymentCallbackReply) GetState() PaymentState {
	if x != nil {
		return x.State
	}
	return PaymentState_PAYMENT_STATE_UNSPECIFIED
}

func (x *VerifyPaymentCallbackReply) GetPaidAmountCents() int64 {
	if x != nil {
		return x.PaidAmountCents
	}
	return 0
}

func (x *VerifyPaymentCallbackReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *VerifyPaymentCallbackReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x0flevis.plugin.v1\"\x8b\x02\n" +
	"\vConfigField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04hint\x18\x03 \x01(\tR\x04hint\x12.\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1a.levis.plugin.v1.FieldTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\bR\x06secret\x12#\n" +
	"\rdefault_value\x18\a \x01(\tR\fdefaultValue\x127\n" +
	"\aoptions\x18\b \x03(\v2\x1d.levis.plugin.v1.SelectOptionR\aoptions\":\n" +
	"\fSelectOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\x11\n" +
	"\x0fDescribeRequest\"\x92\x02\n" +
	"\bManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12?\n" +
	"\fcapabilities\x18\x05 \x03(\x0e2\x1b.levis.plugin.v1.CapabilityR\fcapabilities\x124\n" +
	"\x06config\x18\x06 \x03(\v2\x1c.levis.plugin.v1.ConfigFieldR\x06config\x12'\n" +
	"\x0frequired_scopes\x18\a \x03(\tR\x0erequiredScopes\"\x94\x01\n" +
	"\x10ConfigureRequest\x12E\n" +
	"\x06values\x18\x01 \x03(\v2-.levis.plugin.v1.ConfigureRequest.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\x0eConfigureReply\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"7\n" +
	"\vHealthReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fShutdownRequest\"\x0f\n" +
	"\rShutdownReply\"7\n" +
	"\aMailbox\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8f\x01\n" +
	"\x0fSendMailRequest\x12(\n" +
	"\x02to\x18\x01 \x03(\v2\x18.levis.plugin.v1.MailboxR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\ttext_body\x18\x03 \x01(\tR\btextBody\x12\x1b\n" +
	"\thtml_body\x18\x04 \x01(\tR\bhtmlBody\"\x0f\n" +
	"\rSendMailReply\"\xc8\x01\n" +
	"\x14CreatePaymentRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"return_url\x18\x06 \x01(\tR\treturnUrl\"d\n" +
	"\x12CreatePaymentReply\x12\x17\n" +
	"\apay_url\x18\x01 \x01(\tR\x06payUrl\x12\x1f\n" +
	"\vgateway_ref\x18\x02 \x01(\tR\n" +
	"gatewayRef\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"W\n" +
	"\x13QueryPaymentRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x1f\n" +
	"\vgateway_ref\x18\x02 \x01(\tR\n" +
	"gatewayRef\"\x8e\x01\n" +
	"\x11QueryPaymentReply\x123\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1d.levis.plugin.v1.PaymentStateR\x05state\x12*\n" +
	"\x11paid_amount_cents\x18\x02 \x01(\x03R\x0fpaidAmountCents\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa0\x01\n" +
	"\x1cVerifyPaymentCallbackRequest\x12H\n" +
	"\x03raw\x18\x01 \x03(\v26.levis.plugin.v1.VerifyPaymentCallbackRequest.RawEntryR\x03raw\x1a6\n" +
	"\bRawEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf5\x01\n" +
	"\x1aVerifyPaymentCallbackReply\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x1f\n" +
	"\vgateway_ref\x18\x02 \x01(\tR\n" +
	"gatewayRef\x123\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1d.levis.plugin.v1.PaymentStateR\x05state\x12*\n" +
	"\x11paid_amount_cents\x18\x04 \x01(\x03R\x0fpaidAmountCents\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage*a\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CAPABILITY_SEND_MAIL\x10\x01\x12\x1d\n" +
	"\x19CAPABILITY_CREATE_PAYMENT\x10\x02*\x98\x01\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fFIELD_TYPE_TEXT\x10\x01\x12\x15\n" +
	"\x11FIELD_TYPE_NUMBER\x10\x02\x12\x13\n" +
	"\x0fFIELD_TYPE_BOOL\x10\x03\x12\x15\n" +
	"\x11FIELD_TYPE_SELECT\x10\x04\x12\x17\n" +
	"\x13FIELD_TYPE_TEXTAREA\x10\x05*\x97\x01\n" +
	"\fPaymentState\x12\x1d\n" +
	"\x19PAYMENT_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PAYMENT_STATE_PENDING\x10\x01\x12\x16\n" +
	"\x12PAYMENT_STATE_PAID\x10\x02\x12\x18\n" +
	"\x14PAYMENT_STATE_FAILED\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_STATE_CANCELLED\x10\x042\xb2\x05\n" +
	"\x06Plugin\x12G\n" +
	"\bDescribe\x12 .levis.plugin.v1.DescribeRequest\x1a\x19.levis.plugin.v1.Manifest\x12O\n" +
	"\tConfigure\x12!.levis.plugin.v1.ConfigureRequest\x1a\x1f.levis.plugin.v1.ConfigureReply\x12F\n" +
	"\x06Health\x12\x1e.levis.plugin.v1.HealthRequest\x1a\x1c.levis.plugin.v1.HealthReply\x12L\n" +
	"\bShutdown\x12 .levis.plugin.v1.ShutdownRequest\x1a\x1e.levis.plugin.v1.ShutdownReply\x12L\n" +
	"\bSendMail\x12 .levis.plugin.v1.SendMailRequest\x1a\x1e.levis.plugin.v1.SendMailReply\x12[\n" +
	"\rCreatePayment\x12%.levis.plugin.v1.CreatePaymentRequest\x1a#.levis.plugin.v1.CreatePaymentReply\x12X\n" +
	"\fQueryPayment\x12$.levis.plugin.v1.QueryPaymentRequest\x1a\".levis.plugin.v1.QueryPaymentReply\x12s\n" +
	"\x15VerifyPaymentCallback\x12-.levis.plugin.v1.VerifyPaymentCallbackRequest\x1a+.levis.plugin.v1.VerifyPaymentCallbackReplyB:Z8github.com/SakuraOpenSource/levis/pkg/plugin/proto;protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_plugin_proto_goTypes = []any{
	(Capability)(0),                      // 0: levis.plugin.v1.Capability
	(FieldType)(0),                       // 1: levis.plugin.v1.FieldType
	(PaymentState)(0),                    // 2: levis.plugin.v1.PaymentState
	(*ConfigField)(nil),                  // 3: levis.plugin.v1.ConfigField
	(*SelectOption)(nil),                 // 4: levis.plugin.v1.SelectOption
	(*DescribeRequest)(nil),              // 5: levis.plugin.v1.DescribeRequest
	(*Manifest)(nil),                     // 6: levis.plugin.v1.Manifest
	(*ConfigureRequest)(nil),             // 7: levis.plugin.v1.ConfigureRequest
	(*ConfigureReply)(nil),               // 8: levis.plugin.v1.ConfigureReply
	(*HealthRequest)(nil),                // 9: levis.plugin.v1.HealthRequest
	(*HealthReply)(nil),                  // 10: levis.plugin.v1.HealthReply
	(*ShutdownRequest)(nil),              // 11: levis.plugin.v1.ShutdownRequest
	(*ShutdownReply)(nil),                // 12: levis.plugin.v1.ShutdownReply
	(*Mailbox)(nil),                      // 13: levis.plugin.v1.Mailbox
	(*SendMailRequest)(nil),              // 14: levis.plugin.v1.SendMailRequest
	(*SendMailReply)(nil),                // 15: levis.plugin.v1.SendMailReply
	(*CreatePaymentRequest)(nil),         // 16: levis.plugin.v1.CreatePaymentRequest
	(*CreatePaymentReply)(nil),           // 17: levis.plugin.v1.CreatePaymentReply
	(*QueryPaymentRequest)(nil),          // 18: levis.plugin.v1.QueryPaymentRequest
	(*QueryPaymentReply)(nil),            // 19: levis.plugin.v1.QueryPaymentReply
	(*VerifyPaymentCallbackRequest)(nil), // 20: levis.plugin.v1.VerifyPaymentCallbackRequest
	(*VerifyPaymentCallbackReply)(nil),   // 21: levis.plugin.v1.VerifyPaymentCallbackReply
	nil,                                  // 22: levis.plugin.v1.ConfigureRequest.ValuesEntry
	nil,                                  // 23: levis.plugin.v1.VerifyPaymentCallbackRequest.RawEntry
}
var file_plugin_proto_depIdxs = []int32{
	1,  // 0: levis.plugin.v1.ConfigField.type:type_name -> levis.plugin.v1.FieldType
	4,  // 1: levis.plugin.v1.ConfigField.options:type_name -> levis.plugin.v1.SelectOption
	0,  // 2: levis.plugin.v1.Manifest.capabilities:type_name -> levis.plugin.v1.Capability
	3,  // 3: levis.plugin.v1.Manifest.config:type_name -> levis.plugin.v1.ConfigField
	22, // 4: levis.plugin.v1.ConfigureRequest.values:type_name -> levis.plugin.v1.ConfigureRequest.ValuesEntry
	13, // 5: levis.plugin.v1.SendMailRequest.to:type_name -> levis.plugin.v1.Mailbox
	2,  // 6: levis.plugin.v1.QueryPaymentReply.state:type_name -> levis.plugin.v1.PaymentState
	23, // 7: levis.plugin.v1.VerifyPaymentCallbackRequest.raw:type_name -> levis.plugin.v1.VerifyPaymentCallbackRequest.RawEntry
	2,  // 8: levis.plugin.v1.VerifyPaymentCallbackReply.state:type_name -> levis.plugin.v1.PaymentState
	5,  // 9: levis.plugin.v1.Plugin.Describe:input_type -> levis.plugin.v1.DescribeRequest
	7,  // 10: levis.plugin.v1.Plugin.Configure:input_type -> levis.plugin.v1.ConfigureRequest
	9,  // 11: levis.plugin.v1.Plugin.Health:input_type -> levis.plugin.v1.HealthRequest
	11, // 12: levis.plugin.v1.Plugin.Shutdown:input_type -> levis.plugin.v1.ShutdownRequest
	14, // 13: levis.plugin.v1.Plugin.SendMail:input_type -> levis.plugin.v1.SendMailRequest
	16, // 14: levis.plugin.v1.Plugin.CreatePayment:input_type -> levis.plugin.v1.CreatePaymentRequest
	18, // 15: levis.plugin.v1.Plugin.QueryPayment:input_type -> levis.plugin.v1.QueryPaymentRequest
	20, // 16: levis.plugin.v1.Plugin.VerifyPaymentCallback:input_type -> levis.plugin.v1.VerifyPaymentCallbackRequest
	6,  // 17: levis.plugin.v1.Plugin.Describe:output_type -> levis.plugin.v1.Manifest
	8,  // 18: levis.plugin.v1.Plugin.Configure:output_type -> levis.plugin.v1.ConfigureReply
	10, // 19: levis.plugin.v1.Plugin.Health:output_type -> levis.plugin.v1.HealthReply
	12, // 20: levis.plugin.v1.Plugin.Shutdown:output_type -> levis.plugin.v1.ShutdownReply
	15, // 21: levis.plugin.v1.Plugin.SendMail:output_type -> levis.plugin.v1.SendMailReply
	17, // 22: levis.plugin.v1.Plugin.CreatePayment:output_type -> levis.plugin.v1.CreatePaymentReply
	19, // 23: levis.plugin.v1.Plugin.QueryPayment:output_type -> levis.plugin.v1.QueryPaymentReply
	21, // 24: levis.plugin.v1.Plugin.VerifyPaymentCallback:output_type -> levis.plugin.v1.VerifyPaymentCallbackReply
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
