// Levis 插件契约。
//
// 插件是独立的可执行程序，与主程序通过本文件定义的 gRPC 服务通信。
// 主程序始终是客户端，插件是服务端 —— 插件若要读写 Levis 的数据，
// 走 HTTP 回调 /api/plugin/v1，不在本契约内。
//
// 兼容性约定：字段只增不改，废弃字段用 reserved 占位，绝不复用编号。
// 插件与主程序的版本可能不一致，改动必须让旧插件仍能工作。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Capability 是插件声明的能力。
//
// 每一项对应一组 RPC，主程序据此决定哪些 hook 可以派发给这个插件。
type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED    Capability = 0
	Capability_CAPABILITY_SEND_MAIL      Capability = 1
	Capability_CAPABILITY_CREATE_PAYMENT Capability = 2
	// CAPABILITY_PROVISION_PRODUCT 表示插件可以对接上游供货商：
	// 拉取产品列表、下单、查询订单、管理服务实例。
	Capability_CAPABILITY_PROVISION_PRODUCT Capability = 3
	Capability_CAPABILITY_KYC               Capability = 4
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "CAPABILITY_SEND_MAIL",
		2: "CAPABILITY_CREATE_PAYMENT",
		3: "CAPABILITY_PROVISION_PRODUCT",
		4: "CAPABILITY_KYC",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED":       0,
		"CAPABILITY_SEND_MAIL":         1,
		"CAPABILITY_CREATE_PAYMENT":    2,
		"CAPABILITY_PROVISION_PRODUCT": 3,
		"CAPABILITY_KYC":               4,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// FieldType 是配置项的输入类型，决定后台表单的渲染方式。
type FieldType int32

const (
	FieldType_FIELD_TYPE_UNSPECIFIED FieldType = 0
	FieldType_FIELD_TYPE_TEXT        FieldType = 1
	FieldType_FIELD_TYPE_NUMBER      FieldType = 2
	FieldType_FIELD_TYPE_BOOL        FieldType = 3
	FieldType_FIELD_TYPE_SELECT      FieldType = 4
	// FIELD_TYPE_TEXTAREA 用于私钥、证书这类多行内容。
	FieldType_FIELD_TYPE_TEXTAREA FieldType = 5
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "FIELD_TYPE_TEXT",
		2: "FIELD_TYPE_NUMBER",
		3: "FIELD_TYPE_BOOL",
		4: "FIELD_TYPE_SELECT",
		5: "FIELD_TYPE_TEXTAREA",
	}
	FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"FIELD_TYPE_TEXT":        1,
		"FIELD_TYPE_NUMBER":      2,
		"FIELD_TYPE_BOOL":        3,
		"FIELD_TYPE_SELECT":      4,
		"FIELD_TYPE_TEXTAREA":    5,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

// PaymentState 是一笔支付在渠道侧的状态。
type PaymentState int32

const (
	PaymentState_PAYMENT_STATE_UNSPECIFIED PaymentState = 0
	PaymentState_PAYMENT_STATE_PENDING     PaymentState = 1
	PaymentState_PAYMENT_STATE_PAID        PaymentState = 2
	PaymentState_PAYMENT_STATE_FAILED      PaymentState = 3
	PaymentState_PAYMENT_STATE_CANCELLED   PaymentState = 4
)

// Enum value maps for PaymentState.
var (
	PaymentState_name = map[int32]string{
		0: "PAYMENT_STATE_UNSPECIFIED",
		1: "PAYMENT_STATE_PENDING",
		2: "PAYMENT_STATE_PAID",
		3: "PAYMENT_STATE_FAILED",
		4: "PAYMENT_STATE_CANCELLED",
	}
	PaymentState_value = map[string]int32{
		"PAYMENT_STATE_UNSPECIFIED": 0,
		"PAYMENT_STATE_PENDING":     1,
		"PAYMENT_STATE_PAID":        2,
		"PAYMENT_STATE_FAILED":      3,
		"PAYMENT_STATE_CANCELLED":   4,
	}
)

func (x PaymentState) Enum() *PaymentState {
	p := new(PaymentState)
	*p = x
	return p
}

func (x PaymentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentState) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[2].Descriptor()
}

func (PaymentState) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[2]
}

func (x PaymentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentState.Descriptor instead.
func (PaymentState) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

// HostAction 是对服务实例的操作。
type HostAction int32

const (
	HostAction_HOST_ACTION_UNSPECIFIED HostAction = 0
	HostAction_HOST_ACTION_RENEW       HostAction = 1
	HostAction_HOST_ACTION_SUSPEND     HostAction = 2
	HostAction_HOST_ACTION_UNSUSPEND   HostAction = 3
	HostAction_HOST_ACTION_TERMINATE   HostAction = 4
	// HOST_ACTION_BOOT 开机。
	HostAction_HOST_ACTION_BOOT HostAction = 5
	// HOST_ACTION_SHUTDOWN 关机。
	HostAction_HOST_ACTION_SHUTDOWN HostAction = 6
	// HOST_ACTION_REBOOT 重启。
	HostAction_HOST_ACTION_REBOOT HostAction = 7
	// HOST_ACTION_REINSTALL 重装系统。
	HostAction_HOST_ACTION_REINSTALL HostAction = 8
)

// Enum value maps for HostAction.
var (
	HostAction_name = map[int32]string{
		0: "HOST_ACTION_UNSPECIFIED",
		1: "HOST_ACTION_RENEW",
		2: "HOST_ACTION_SUSPEND",
		3: "HOST_ACTION_UNSUSPEND",
		4: "HOST_ACTION_TERMINATE",
		5: "HOST_ACTION_BOOT",
		6: "HOST_ACTION_SHUTDOWN",
		7: "HOST_ACTION_REBOOT",
		8: "HOST_ACTION_REINSTALL",
	}
	HostAction_value = map[string]int32{
		"HOST_ACTION_UNSPECIFIED": 0,
		"HOST_ACTION_RENEW":       1,
		"HOST_ACTION_SUSPEND":     2,
		"HOST_ACTION_UNSUSPEND":   3,
		"HOST_ACTION_TERMINATE":   4,
		"HOST_ACTION_BOOT":        5,
		"HOST_ACTION_SHUTDOWN":    6,
		"HOST_ACTION_REBOOT":      7,
		"HOST_ACTION_REINSTALL":   8,
	}
)

func (x HostAction) Enum() *HostAction {
	p := new(HostAction)
	*p = x
	return p
}

func (x HostAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostAction) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[3].Descriptor()
}

func (HostAction) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[3]
}

func (x HostAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostAction.Descriptor instead.
func (HostAction) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

// ConfigField 描述一个配置项。插件用它告诉后台该渲染什么表单。
type ConfigField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key 是配置项标识，主程序按 (插件 ID, key) 落库。
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// label 是表单上显示的名称。
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// hint 是字段下方的补充说明，可为空。
	Hint     string    `protobuf:"bytes,3,opt,name=hint,proto3" json:"hint,omitempty"`
	Type     FieldType `protobuf:"varint,4,opt,name=type,proto3,enum=levis.plugin.v1.FieldType" json:"type,omitempty"`
	Required bool      `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	// secret 为 true 时，接口永不回传该项的值，后台渲染为密码框。
	// SMTP 密码、渠道私钥都应当置为 true。
	Secret bool `protobuf:"varint,6,opt,name=secret,proto3" json:"secret,omitempty"`
	// default_value 在管理员未填写时作为初始值展示。
	// secret 字段不应给默认值。
	DefaultValue string `protobuf:"bytes,7,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// options 仅在 FIELD_TYPE_SELECT 时有意义。
	Options       []*SelectOption `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigField) Reset() {
	*x = ConfigField{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigField) ProtoMessage() {}

func (x *ConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigField.ProtoReflect.Descriptor instead.
func (*ConfigField) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ConfigField) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *ConfigField) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *ConfigField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigField) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *ConfigField) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ConfigField) GetOptions() []*SelectOption {
	if x != nil {
		return x.Options
	}
	return nil
}

// SelectOption 是下拉框的一个选项。
type SelectOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectOption) Reset() {
	*x = SelectOption{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectOption) ProtoMessage() {}

func (x *SelectOption) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectOption.ProtoReflect.Descriptor instead.
func (*SelectOption) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *SelectOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SelectOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

// Manifest 是插件的自我描述。
type Manifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 是展示名，如「SMTP 邮件发送」。
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version 是插件自己的版本号，仅用于展示与排错。
	Version     string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// author 可为空。
	Author       string         `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Capabilities []Capability   `protobuf:"varint,5,rep,packed,name=capabilities,proto3,enum=levis.plugin.v1.Capability" json:"capabilities,omitempty"`
	Config       []*ConfigField `protobuf:"bytes,6,rep,name=config,proto3" json:"config,omitempty"`
	// required_scopes 是插件回调 /api/plugin/v1 所需的权限位，
	// 取值见 model.PluginScope*。主程序据此签发 Key，管理员可见。
	RequiredScopes []string `protobuf:"bytes,7,rep,name=required_scopes,json=requiredScopes,proto3" json:"required_scopes,omitempty"`
	// payment_config 是按支付方式实例填写的配置项（如 epay 的 PID/KEY）。
	// 与全局 config 区分：同一支付插件可被多个支付方式复用，每个支付方式
	// 携带一套独立的 payment_config 值，经 CreatePayment 等请求传入。
	PaymentConfig []*ConfigField `protobuf:"bytes,8,rep,name=payment_config,json=paymentConfig,proto3" json:"payment_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manifest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manifest) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Manifest) GetConfig() []*ConfigField {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Manifest) GetRequiredScopes() []string {
	if x != nil {
		return x.RequiredScopes
	}
	return nil
}

func (x *Manifest) GetPaymentConfig() []*ConfigField {
	if x != nil {
		return x.PaymentConfig
	}
	return nil
}

type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values 是配置项的当前值，键为 ConfigField.key。
	//
	// 一律用字符串传递，由插件按自己声明的 type 解析：数字与布尔在这里
	// 不值得为其各开一个字段，插件本来就知道自己要什么类型。
	Values        map[string]string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureRequest) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ConfigureReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error 非空表示配置不可用（比如 SMTP 连不上），主程序会把它显示在
	// 后台并把插件标为异常。不要用 gRPC 错误返回这类信息 —— 配置错误是
	// 预期内的结果，不是调用失败。
	Error         string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureReply) Reset() {
	*x = ConfigureReply{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureReply) ProtoMessage() {}

func (x *ConfigureReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureReply.ProtoReflect.Descriptor instead.
func (*ConfigureReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigureReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

type HealthReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// message 在 ok 为 false 时说明原因。
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReply) Reset() {
	*x = HealthReply{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReply) ProtoMessage() {}

func (x *HealthReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReply.ProtoReflect.Descriptor instead.
func (*HealthReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *HealthReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

type ShutdownReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownReply) Reset() {
	*x = ShutdownReply{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownReply) ProtoMessage() {}

func (x *ShutdownReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownReply.ProtoReflect.Descriptor instead.
func (*ShutdownReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

// Mailbox 是一个收件人。
type Mailbox struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// name 可为空，为空时只用地址。
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mailbox) Reset() {
	*x = Mailbox{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mailbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mailbox) ProtoMessage() {}

func (x *Mailbox) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mailbox.ProtoReflect.Descriptor instead.
func (*Mailbox) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *Mailbox) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Mailbox) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SendMailRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	To      []*Mailbox             `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Subject string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// text_body 是纯文本正文，始终提供。
	TextBody string `protobuf:"bytes,3,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	// html_body 可为空；插件应在为空时只发纯文本。
	HtmlBody      string `protobuf:"bytes,4,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailRequest) Reset() {
	*x = SendMailRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailRequest) ProtoMessage() {}

func (x *SendMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailRequest.ProtoReflect.Descriptor instead.
func (*SendMailRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *SendMailRequest) GetTo() []*Mailbox {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendMailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendMailRequest) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *SendMailRequest) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

type SendMailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailReply) Reset() {
	*x = SendMailReply{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailReply) ProtoMessage() {}

func (x *SendMailReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailReply.ProtoReflect.Descriptor instead.
func (*SendMailReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

type CreatePaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// external_id 由主程序生成，插件必须在回调 /api/plugin/v1/wallet/credit
	// 时原样带回 —— 它是加钱幂等的依据，渠道重复回调时靠它去重。
	ExternalId string `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// amount_cents 是金额，整数分。全系统不使用浮点表示金额。
	AmountCents int64 `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	// currency 是 ISO 4217 代码，如 CNY。
	Currency string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	// subject 是给用户看的付款说明。
	Subject string `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	UserId  uint64 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// return_url 是用户付完款后应当跳回的站内地址。
	ReturnUrl string `protobuf:"bytes,6,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	// client_ip 是用户的客户端 IP，部分支付渠道要求此字段。
	ClientIp string `protobuf:"bytes,7,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	// config 是按支付方式实例传入的插件配置（如 epay 的 PID/KEY），
	// 覆盖全局 Configure 的同名配置。
	Config map[string]string `protobuf:"bytes,8,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// notify_url 是上游回调地址，由主程序按支付方式构造。
	NotifyUrl     string `protobuf:"bytes,9,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePaymentRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreatePaymentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePaymentRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *CreatePaymentRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *CreatePaymentRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreatePaymentRequest) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

type CreatePaymentReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pay_url 是让用户跳转过去完成支付的地址。
	PayUrl string `protobuf:"bytes,1,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	// gateway_ref 是渠道侧的单号，落库备查，可为空。
	GatewayRef string `protobuf:"bytes,2,opt,name=gateway_ref,json=gatewayRef,proto3" json:"gateway_ref,omitempty"`
	// error 非空表示创建失败且原因可以展示给用户（如「金额低于渠道下限」）。
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReply) Reset() {
	*x = CreatePaymentReply{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReply) ProtoMessage() {}

func (x *CreatePaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReply.ProtoReflect.Descriptor instead.
func (*CreatePaymentReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePaymentReply) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *CreatePaymentReply) GetGatewayRef() string {
	if x != nil {
		return x.GatewayRef
	}
	return ""
}

func (x *CreatePaymentReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QueryPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	GatewayRef    string                 `protobuf:"bytes,2,opt,name=gateway_ref,json=gatewayRef,proto3" json:"gateway_ref,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentRequest) Reset() {
	*x = QueryPaymentRequest{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentRequest) ProtoMessage() {}

func (x *QueryPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentRequest.ProtoReflect.Descriptor instead.
func (*QueryPaymentRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *QueryPaymentRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *QueryPaymentRequest) GetGatewayRef() string {
	if x != nil {
		return x.GatewayRef
	}
	return ""
}

func (x *QueryPaymentRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type QueryPaymentReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State PaymentState           `protobuf:"varint,1,opt,name=state,proto3,enum=levis.plugin.v1.PaymentState" json:"state,omitempty"`
	// paid_amount_cents 是渠道实际收到的金额，整数分。
	//
	// 主程序会核对它与请求金额是否一致：不一致时不入账并记录告警，
	// 避免「付一分钱开通一年」这类少付攻击。
	PaidAmountCents int64  `protobuf:"varint,2,opt,name=paid_amount_cents,json=paidAmountCents,proto3" json:"paid_amount_cents,omitempty"`
	Message         string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryPaymentReply) Reset() {
	*x = QueryPaymentReply{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentReply) ProtoMessage() {}

func (x *QueryPaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentReply.ProtoReflect.Descriptor instead.
func (*QueryPaymentReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *QueryPaymentReply) GetState() PaymentState {
	if x != nil {
		return x.State
	}
	return PaymentState_PAYMENT_STATE_UNSPECIFIED
}

func (x *QueryPaymentReply) GetPaidAmountCents() int64 {
	if x != nil {
		return x.PaidAmountCents
	}
	return 0
}

func (x *QueryPaymentReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyPaymentCallbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// raw 是渠道通知的原始表单或 JSON 字段，主程序不解释其含义。
	Raw           map[string]string `protobuf:"bytes,1,rep,name=raw,proto3" json:"raw,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Config        map[string]string `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPaymentCallbackRequest) Reset() {
	*x = VerifyPaymentCallbackRequest{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentCallbackRequest) ProtoMessage() {}

func (x *VerifyPaymentCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentCallbackRequest.ProtoReflect.Descriptor instead.
func (*VerifyPaymentCallbackRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *VerifyPaymentCallbackRequest) GetRaw() map[string]string {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *VerifyPaymentCallbackRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type VerifyPaymentCallbackReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// external_id 必须是 CreatePaymentRequest 下发的商户单号。
	ExternalId string `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// gateway_ref 是渠道侧流水号，可为空。
	GatewayRef      string       `protobuf:"bytes,2,opt,name=gateway_ref,json=gatewayRef,proto3" json:"gateway_ref,omitempty"`
	State           PaymentState `protobuf:"varint,3,opt,name=state,proto3,enum=levis.plugin.v1.PaymentState" json:"state,omitempty"`
	PaidAmountCents int64        `protobuf:"varint,4,opt,name=paid_amount_cents,json=paidAmountCents,proto3" json:"paid_amount_cents,omitempty"`
	// currency 可为空；非空时主程序必须核对为 CNY。
	Currency      string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Message       string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPaymentCallbackReply) Reset() {
	*x = VerifyPaymentCallbackReply{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentCallbackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentCallbackReply) ProtoMessage() {}

func (x *VerifyPaymentCallbackReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentCallbackReply.ProtoReflect.Descriptor instead.
func (*VerifyPaymentCallbackReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *VerifyPaymentCallbackReply) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *VerifyPaymentCallbackReply) GetGatewayRef() string {
	if x != nil {
		return x.GatewayRef
	}
	return ""
}

func (x *VerifyPaymentCallbackReply) GetState() PaymentState {
	if x != nil {
		return x.State
	}
	return PaymentState_PAYMENT_STATE_UNSPECIFIED
}

func (x *VerifyPaymentCallbackReply) GetPaidAmountCents() int64 {
	if x != nil {
		return x.PaidAmountCents
	}
	return 0
}

func (x *VerifyPaymentCallbackReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *VerifyPaymentCallbackReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListProductsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// page 从 1 开始。
	Page          int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// UpstreamProduct 是上游返回的一个产品。
type UpstreamProduct struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// price_cents 是金额，整数分。
	PriceCents int64 `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	// billing_cycle 是计费周期：monthly / quarterly / annually / biennially / triennially。
	BillingCycle string `protobuf:"bytes,5,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"`
	// group_name 是产品分组名，如「香港云服务器」。
	GroupName string `protobuf:"bytes,6,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	// specs 是规格的键值对，如 {"CPU":"4核","内存":"8GB","带宽":"10Mbps"}。
	Specs map[string]string `protobuf:"bytes,7,rep,name=specs,proto3" json:"specs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// stock_available 为 true 表示可购买。
	StockAvailable bool `protobuf:"varint,8,opt,name=stock_available,json=stockAvailable,proto3" json:"stock_available,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpstreamProduct) Reset() {
	*x = UpstreamProduct{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamProduct) ProtoMessage() {}

func (x *UpstreamProduct) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamProduct.ProtoReflect.Descriptor instead.
func (*UpstreamProduct) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *UpstreamProduct) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpstreamProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpstreamProduct) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpstreamProduct) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *UpstreamProduct) GetBillingCycle() string {
	if x != nil {
		return x.BillingCycle
	}
	return ""
}

func (x *UpstreamProduct) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *UpstreamProduct) GetSpecs() map[string]string {
	if x != nil {
		return x.Specs
	}
	return nil
}

func (x *UpstreamProduct) GetStockAvailable() bool {
	if x != nil {
		return x.StockAvailable
	}
	return false
}

type ListProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*UpstreamProduct     `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReply) Reset() {
	*x = ListProductsReply{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReply) ProtoMessage() {}

func (x *ListProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReply.ProtoReflect.Descriptor instead.
func (*ListProductsReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *ListProductsReply) GetProducts() []*UpstreamProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *UpstreamProduct       `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReply) Reset() {
	*x = GetProductReply{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReply) ProtoMessage() {}

func (x *GetProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReply.ProtoReflect.Descriptor instead.
func (*GetProductReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *GetProductReply) GetProduct() *UpstreamProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *GetProductReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// product_id 是上游产品 ID。
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	// billing_cycle 是计费周期。
	BillingCycle string `protobuf:"bytes,2,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"`
	Quantity     int32  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// client_email 是下游客户邮箱，上游可能用它创建账号。
	ClientEmail string `protobuf:"bytes,4,opt,name=client_email,json=clientEmail,proto3" json:"client_email,omitempty"`
	// remark 是备注，主程序会填入 Levis 订单号。
	Remark        string `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *CreateOrderRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateOrderRequest) GetBillingCycle() string {
	if x != nil {
		return x.BillingCycle
	}
	return ""
}

func (x *CreateOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderRequest) GetClientEmail() string {
	if x != nil {
		return x.ClientEmail
	}
	return ""
}

func (x *CreateOrderRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateOrderReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// upstream_order_id 是上游返回的订单号，后续查询与管理都用它。
	UpstreamOrderId string `protobuf:"bytes,1,opt,name=upstream_order_id,json=upstreamOrderId,proto3" json:"upstream_order_id,omitempty"`
	// upstream_order_no 是上游供展示的订单编号。
	UpstreamOrderNo string `protobuf:"bytes,2,opt,name=upstream_order_no,json=upstreamOrderNo,proto3" json:"upstream_order_no,omitempty"`
	// total_cents 是上游返回的订单金额，主程序会核对。
	TotalCents int64 `protobuf:"varint,3,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	// status 是上游订单状态：pending / paid / active / cancelled 等。
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReply) Reset() {
	*x = CreateOrderReply{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReply) ProtoMessage() {}

func (x *CreateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReply.ProtoReflect.Descriptor instead.
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *CreateOrderReply) GetUpstreamOrderId() string {
	if x != nil {
		return x.UpstreamOrderId
	}
	return ""
}

func (x *CreateOrderReply) GetUpstreamOrderNo() string {
	if x != nil {
		return x.UpstreamOrderNo
	}
	return ""
}

func (x *CreateOrderReply) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *CreateOrderReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateOrderReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UpstreamOrderId string                 `protobuf:"bytes,1,opt,name=upstream_order_id,json=upstreamOrderId,proto3" json:"upstream_order_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *GetOrderRequest) GetUpstreamOrderId() string {
	if x != nil {
		return x.UpstreamOrderId
	}
	return ""
}

type GetOrderReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UpstreamOrderId string                 `protobuf:"bytes,1,opt,name=upstream_order_id,json=upstreamOrderId,proto3" json:"upstream_order_id,omitempty"`
	UpstreamOrderNo string                 `protobuf:"bytes,2,opt,name=upstream_order_no,json=upstreamOrderNo,proto3" json:"upstream_order_no,omitempty"`
	TotalCents      int64                  `protobuf:"varint,3,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// host_id 是上游开通后返回的服务实例 ID，为空表示尚未开通。
	HostId        string `protobuf:"bytes,5,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReply) Reset() {
	*x = GetOrderReply{}
	mi := &file_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReply) ProtoMessage() {}

func (x *GetOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReply.ProtoReflect.Descriptor instead.
func (*GetOrderReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *GetOrderReply) GetUpstreamOrderId() string {
	if x != nil {
		return x.UpstreamOrderId
	}
	return ""
}

func (x *GetOrderReply) GetUpstreamOrderNo() string {
	if x != nil {
		return x.UpstreamOrderNo
	}
	return ""
}

func (x *GetOrderReply) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *GetOrderReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderReply) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *GetOrderReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ManageHostRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	HostId string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Action HostAction             `protobuf:"varint,2,opt,name=action,proto3,enum=levis.plugin.v1.HostAction" json:"action,omitempty"`
	// billing_cycle 仅在 RENEW 时需要。
	BillingCycle string `protobuf:"bytes,3,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"`
	// os 仅在 REINSTALL 时需要，表示要重装的系统 ID。
	Os            string `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageHostRequest) Reset() {
	*x = ManageHostRequest{}
	mi := &file_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageHostRequest) ProtoMessage() {}

func (x *ManageHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageHostRequest.ProtoReflect.Descriptor instead.
func (*ManageHostRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *ManageHostRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ManageHostRequest) GetAction() HostAction {
	if x != nil {
		return x.Action
	}
	return HostAction_HOST_ACTION_UNSPECIFIED
}

func (x *ManageHostRequest) GetBillingCycle() string {
	if x != nil {
		return x.BillingCycle
	}
	return ""
}

func (x *ManageHostRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type ManageHostReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success 为 true 表示操作成功。
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// new_expiry 是续费后的新到期时间（RFC3339），仅在 RENEW 成功时返回。
	NewExpiry     string `protobuf:"bytes,2,opt,name=new_expiry,json=newExpiry,proto3" json:"new_expiry,omitempty"`
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageHostReply) Reset() {
	*x = ManageHostReply{}
	mi := &file_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageHostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageHostReply) ProtoMessage() {}

func (x *ManageHostReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageHostReply.ProtoReflect.Descriptor instead.
func (*ManageHostReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *ManageHostReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ManageHostReply) GetNewExpiry() string {
	if x != nil {
		return x.NewExpiry
	}
	return ""
}

func (x *ManageHostReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostRequest) Reset() {
	*x = GetHostRequest{}
	mi := &file_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostRequest) ProtoMessage() {}

func (x *GetHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostRequest.ProtoReflect.Descriptor instead.
func (*GetHostRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *GetHostRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type UpstreamHost struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId    string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName  string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Status       string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	BillingCycle string                 `protobuf:"bytes,5,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"`
	// expiry 是到期时间（RFC3339）。
	Expiry string `protobuf:"bytes,6,opt,name=expiry,proto3" json:"expiry,omitempty"`
	// upstream_order_id 是关联的上游订单号。
	UpstreamOrderId string `protobuf:"bytes,7,opt,name=upstream_order_id,json=upstreamOrderId,proto3" json:"upstream_order_id,omitempty"`
	// actions 是上游支持的操作列表，如 on/off/reboot/reinstall。
	Actions       []string `protobuf:"bytes,8,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamHost) Reset() {
	*x = UpstreamHost{}
	mi := &file_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamHost) ProtoMessage() {}

func (x *UpstreamHost) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamHost.ProtoReflect.Descriptor instead.
func (*UpstreamHost) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{31}
}

func (x *UpstreamHost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpstreamHost) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpstreamHost) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *UpstreamHost) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpstreamHost) GetBillingCycle() string {
	if x != nil {
		return x.BillingCycle
	}
	return ""
}

func (x *UpstreamHost) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *UpstreamHost) GetUpstreamOrderId() string {
	if x != nil {
		return x.UpstreamOrderId
	}
	return ""
}

func (x *UpstreamHost) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

type GetHostReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *UpstreamHost          `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostReply) Reset() {
	*x = GetHostReply{}
	mi := &file_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostReply) ProtoMessage() {}

func (x *GetHostReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostReply.ProtoReflect.Descriptor instead.
func (*GetHostReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{32}
}

func (x *GetHostReply) GetHost() *UpstreamHost {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *GetHostReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OSImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSImage) Reset() {
	*x = OSImage{}
	mi := &file_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSImage) ProtoMessage() {}

func (x *OSImage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSImage.ProtoReflect.Descriptor instead.
func (*OSImage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{33}
}

func (x *OSImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OSImage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OSImage) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type ListHostOSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostOSRequest) Reset() {
	*x = ListHostOSRequest{}
	mi := &file_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostOSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostOSRequest) ProtoMessage() {}

func (x *ListHostOSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostOSRequest.ProtoReflect.Descriptor instead.
func (*ListHostOSRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{34}
}

func (x *ListHostOSRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type ListHostOSReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            []*OSImage             `protobuf:"bytes,1,rep,name=os,proto3" json:"os,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostOSReply) Reset() {
	*x = ListHostOSReply{}
	mi := &file_plugin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostOSReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostOSReply) ProtoMessage() {}

func (x *ListHostOSReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostOSReply.ProtoReflect.Descriptor instead.
func (*ListHostOSReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{35}
}

func (x *ListHostOSReply) GetOs() []*OSImage {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *ListHostOSReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartKYCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IdCard        string                 `protobuf:"bytes,2,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartKYCRequest) Reset() {
	*x = StartKYCRequest{}
	mi := &file_plugin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartKYCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartKYCRequest) ProtoMessage() {}

func (x *StartKYCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartKYCRequest.ProtoReflect.Descriptor instead.
func (*StartKYCRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{36}
}

func (x *StartKYCRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartKYCRequest) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *StartKYCRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type StartKYCReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertifyId     string                 `protobuf:"bytes,1,opt,name=certify_id,json=certifyId,proto3" json:"certify_id,omitempty"`
	CertifyHtml   string                 `protobuf:"bytes,2,opt,name=certify_html,json=certifyHtml,proto3" json:"certify_html,omitempty"`
	CertifyUrl    string                 `protobuf:"bytes,3,opt,name=certify_url,json=certifyUrl,proto3" json:"certify_url,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartKYCReply) Reset() {
	*x = StartKYCReply{}
	mi := &file_plugin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartKYCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartKYCReply) ProtoMessage() {}

func (x *StartKYCReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartKYCReply.ProtoReflect.Descriptor instead.
func (*StartKYCReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{37}
}

func (x *StartKYCReply) GetCertifyId() string {
	if x != nil {
		return x.CertifyId
	}
	return ""
}

func (x *StartKYCReply) GetCertifyHtml() string {
	if x != nil {
		return x.CertifyHtml
	}
	return ""
}

func (x *StartKYCReply) GetCertifyUrl() string {
	if x != nil {
		return x.CertifyUrl
	}
	return ""
}

func (x *StartKYCReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryKYCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertifyId     string                 `protobuf:"bytes,1,opt,name=certify_id,json=certifyId,proto3" json:"certify_id,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryKYCRequest) Reset() {
	*x = QueryKYCRequest{}
	mi := &file_plugin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKYCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKYCRequest) ProtoMessage() {}

func (x *QueryKYCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKYCRequest.ProtoReflect.Descriptor instead.
func (*QueryKYCRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{38}
}

func (x *QueryKYCRequest) GetCertifyId() string {
	if x != nil {
		return x.CertifyId
	}
	return ""
}

func (x *QueryKYCRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type QueryKYCReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// passed: T 通过，F 未通过，P 处理中。
	Passed        string `protobuf:"bytes,1,opt,name=passed,proto3" json:"passed,omitempty"`
	IdentityInfo  string `protobuf:"bytes,2,opt,name=identity_info,json=identityInfo,proto3" json:"identity_info,omitempty"`
	MaterialInfo  string `protobuf:"bytes,3,opt,name=material_info,json=materialInfo,proto3" json:"material_info,omitempty"`
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryKYCReply) Reset() {
	*x = QueryKYCReply{}
	mi := &file_plugin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKYCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKYCReply) ProtoMessage() {}

func (x *QueryKYCReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKYCReply.ProtoReflect.Descriptor instead.
func (*QueryKYCReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{39}
}

func (x *QueryKYCReply) GetPassed() string {
	if x != nil {
		return x.Passed
	}
	return ""
}

func (x *QueryKYCReply) GetIdentityInfo() string {
	if x != nil {
		return x.IdentityInfo
	}
	return ""
}

func (x *QueryKYCReply) GetMaterialInfo() string {
	if x != nil {
		return x.MaterialInfo
	}
	return ""
}

func (x *QueryKYCReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x0flevis.plugin.v1\"\x8b\x02\n" +
	"\vConfigField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04hint\x18\x03 \x01(\tR\x04hint\x12.\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1a.levis.plugin.v1.FieldTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\bR\x06secret\x12#\n" +
	"\rdefault_value\x18\a \x01(\tR\fdefaultValue\x127\n" +
	"\aoptions\x18\b \x03(\v2\x1d.levis.plugin.v1.SelectOptionR\aoptions\":\n" +
	"\fSelectOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\x11\n" +
	"\x0fDescribeRequest\"\xd7\x02\n" +
	"\bManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12?\n" +
	"\fcapabilities\x18\x05 \x03(\x0e2\x1b.levis.plugin.v1.CapabilityR\fcapabilities\x124\n" +
	"\x06config\x18\x06 \x03(\v2\x1c.levis.plugin.v1.ConfigFieldR\x06config\x12'\n" +
	"\x0frequired_scopes\x18\a \x03(\tR\x0erequiredScopes\x12C\n" +
	"\x0epayment_config\x18\b \x03(\v2\x1c.levis.plugin.v1.ConfigFieldR\rpaymentConfig\"\x94\x01\n" +
	"\x10ConfigureRequest\x12E\n" +
	"\x06values\x18\x01 \x03(\v2-.levis.plugin.v1.ConfigureRequest.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\x0eConfigureReply\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"7\n" +
	"\vHealthReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fShutdownRequest\"\x0f\n" +
	"\rShutdownReply\"7\n" +
	"\aMailbox\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8f\x01\n" +
	"\x0fSendMailRequest\x12(\n" +
	"\x02to\x18\x01 \x03(\v2\x18.levis.plugin.v1.MailboxR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\ttext_body\x18\x03 \x01(\tR\btextBody\x12\x1b\n" +
	"\thtml_body\x18\x04 \x01(\tR\bhtmlBody\"\x0f\n" +
	"\rSendMailReply\"\x8a\x03\n" +
	"\x14CreatePaymentRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"return_url\x18\x06 \x01(\tR\treturnUrl\x12\x1b\n" +
	"\tclient_ip\x18\a \x01(\tR\bclientIp\x12I\n" +
	"\x06config\x18\b \x03(\v21.levis.plugin.v1.CreatePaymentRequest.ConfigEntryR\x06config\x12\x1d\n" +
	"\n" +
	"notify_url\x18\t \x01(\tR\tnotifyUrl\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x12CreatePaymentReply\x12\x17\n" +
	"\apay_url\x18\x01 \x01(\tR\x06payUrl\x12\x1f\n" +
	"\vgateway_ref\x18\x02 \x01(\tR\n" +
	"gatewayRef\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xdc\x01\n" +
	"\x13QueryPaymentRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x1f\n" +
	"\vgateway_ref\x18\x02 \x01(\tR\n" +
	"gatewayRef\x12H\n" +
	"\x06config\x18\x03 \x03(\v20.levis.plugin.v1.QueryPaymentRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x11QueryPaymentReply\x123\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1d.levis.plugin.v1.PaymentStateR\x05state\x12*\n" +
	"\x11paid_amount_cents\x18\x02 \x01(\x03R\x0fpaidAmountCents\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xae\x02\n" +
	"\x1cVerifyPaymentCallbackRequest\x12H\n" +
	"\x03raw\x18\x01 \x03(\v26.levis.plugin.v1.VerifyPaymentCallbackRequest.RawEntryR\x03raw\x12Q\n" +
	"\x06config\x18\x02 \x03(\v29.levis.plugin.v1.VerifyPaymentCallbackRequest.ConfigEntryR\x06config\x1a6\n" +
	"\bRawEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf5\x01\n" +
	"\x1aVerifyPaymentCallbackReply\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x1f\n" +
	"\vgateway_ref\x18\x02 \x01(\tR\n" +
	"gatewayRef\x123\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1d.levis.plugin.v1.PaymentStateR\x05state\x12*\n" +
	"\x11paid_amount_cents\x18\x04 \x01(\x03R\x0fpaidAmountCents\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"?\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xe2\x02\n" +
	"\x0fUpstreamProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x03R\n" +
	"priceCents\x12#\n" +
	"\rbilling_cycle\x18\x05 \x01(\tR\fbillingCycle\x12\x1d\n" +
	"\n" +
	"group_name\x18\x06 \x01(\tR\tgroupName\x12A\n" +
	"\x05specs\x18\a \x03(\v2+.levis.plugin.v1.UpstreamProduct.SpecsEntryR\x05specs\x12'\n" +
	"\x0fstock_available\x18\b \x01(\bR\x0estockAvailable\x1a8\n" +
	"\n" +
	"SpecsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\x11ListProductsReply\x12<\n" +
	"\bproducts\x18\x01 \x03(\v2 .levis.plugin.v1.UpstreamProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"c\n" +
	"\x0fGetProductReply\x12:\n" +
	"\aproduct\x18\x01 \x01(\v2 .levis.plugin.v1.UpstreamProductR\aproduct\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xaf\x01\n" +
	"\x12CreateOrderRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\rbilling_cycle\x18\x02 \x01(\tR\fbillingCycle\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12!\n" +
	"\fclient_email\x18\x04 \x01(\tR\vclientEmail\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\"\xb9\x01\n" +
	"\x10CreateOrderReply\x12*\n" +
	"\x11upstream_order_id\x18\x01 \x01(\tR\x0fupstreamOrderId\x12*\n" +
	"\x11upstream_order_no\x18\x02 \x01(\tR\x0fupstreamOrderNo\x12\x1f\n" +
	"\vtotal_cents\x18\x03 \x01(\x03R\n" +
	"totalCents\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"=\n" +
	"\x0fGetOrderRequest\x12*\n" +
	"\x11upstream_order_id\x18\x01 \x01(\tR\x0fupstreamOrderId\"\xcf\x01\n" +
	"\rGetOrderReply\x12*\n" +
	"\x11upstream_order_id\x18\x01 \x01(\tR\x0fupstreamOrderId\x12*\n" +
	"\x11upstream_order_no\x18\x02 \x01(\tR\x0fupstreamOrderNo\x12\x1f\n" +
	"\vtotal_cents\x18\x03 \x01(\x03R\n" +
	"totalCents\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x17\n" +
	"\ahost_id\x18\x05 \x01(\tR\x06hostId\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x96\x01\n" +
	"\x11ManageHostRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x123\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1b.levis.plugin.v1.HostActionR\x06action\x12#\n" +
	"\rbilling_cycle\x18\x03 \x01(\tR\fbillingCycle\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\"`\n" +
	"\x0fManageHostReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"new_expiry\x18\x02 \x01(\tR\tnewExpiry\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\")\n" +
	"\x0eGetHostRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\"\xfb\x01\n" +
	"\fUpstreamHost\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rbilling_cycle\x18\x05 \x01(\tR\fbillingCycle\x12\x16\n" +
	"\x06expiry\x18\x06 \x01(\tR\x06expiry\x12*\n" +
	"\x11upstream_order_id\x18\a \x01(\tR\x0fupstreamOrderId\x12\x18\n" +
	"\aactions\x18\b \x03(\tR\aactions\"W\n" +
	"\fGetHostReply\x121\n" +
	"\x04host\x18\x01 \x01(\v2\x1d.levis.plugin.v1.UpstreamHostR\x04host\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"C\n" +
	"\aOSImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\",\n" +
	"\x11ListHostOSRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\"Q\n" +
	"\x0fListHostOSReply\x12(\n" +
	"\x02os\x18\x01 \x03(\v2\x18.levis.plugin.v1.OSImageR\x02os\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xbf\x01\n" +
	"\x0fStartKYCRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\aid_card\x18\x02 \x01(\tR\x06idCard\x12D\n" +
	"\x06config\x18\x03 \x03(\v2,.levis.plugin.v1.StartKYCRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x01\n" +
	"\rStartKYCReply\x12\x1d\n" +
	"\n" +
	"certify_id\x18\x01 \x01(\tR\tcertifyId\x12!\n" +
	"\fcertify_html\x18\x02 \x01(\tR\vcertifyHtml\x12\x1f\n" +
	"\vcertify_url\x18\x03 \x01(\tR\n" +
	"certifyUrl\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xb1\x01\n" +
	"\x0fQueryKYCRequest\x12\x1d\n" +
	"\n" +
	"certify_id\x18\x01 \x01(\tR\tcertifyId\x12D\n" +
	"\x06config\x18\x02 \x03(\v2,.levis.plugin.v1.QueryKYCRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\rQueryKYCReply\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\tR\x06passed\x12#\n" +
	"\ridentity_info\x18\x02 \x01(\tR\fidentityInfo\x12#\n" +
	"\rmaterial_info\x18\x03 \x01(\tR\fmaterialInfo\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage*\x97\x01\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CAPABILITY_SEND_MAIL\x10\x01\x12\x1d\n" +
	"\x19CAPABILITY_CREATE_PAYMENT\x10\x02\x12 \n" +
	"\x1cCAPABILITY_PROVISION_PRODUCT\x10\x03\x12\x12\n" +
	"\x0eCAPABILITY_KYC\x10\x04*\x98\x01\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fFIELD_TYPE_TEXT\x10\x01\x12\x15\n" +
	"\x11FIELD_TYPE_NUMBER\x10\x02\x12\x13\n" +
	"\x0fFIELD_TYPE_BOOL\x10\x03\x12\x15\n" +
	"\x11FIELD_TYPE_SELECT\x10\x04\x12\x17\n" +
	"\x13FIELD_TYPE_TEXTAREA\x10\x05*\x97\x01\n" +
	"\fPaymentState\x12\x1d\n" +
	"\x19PAYMENT_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PAYMENT_STATE_PENDING\x10\x01\x12\x16\n" +
	"\x12PAYMENT_STATE_PAID\x10\x02\x12\x18\n" +
	"\x14PAYMENT_STATE_FAILED\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_STATE_CANCELLED\x10\x04*\xf2\x01\n" +
	"\n" +
	"HostAction\x12\x1b\n" +
	"\x17HOST_ACTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11HOST_ACTION_RENEW\x10\x01\x12\x17\n" +
	"\x13HOST_ACTION_SUSPEND\x10\x02\x12\x19\n" +
	"\x15HOST_ACTION_UNSUSPEND\x10\x03\x12\x19\n" +
	"\x15HOST_ACTION_TERMINATE\x10\x04\x12\x14\n" +
	"\x10HOST_ACTION_BOOT\x10\x05\x12\x18\n" +
	"\x14HOST_ACTION_SHUTDOWN\x10\x06\x12\x16\n" +
	"\x12HOST_ACTION_REBOOT\x10\a\x12\x19\n" +
	"\x15HOST_ACTION_REINSTALL\x10\b2\x94\v\n" +
	"\x06Plugin\x12G\n" +
	"\bDescribe\x12 .levis.plugin.v1.DescribeRequest\x1a\x19.levis.plugin.v1.Manifest\x12O\n" +
	"\tConfigure\x12!.levis.plugin.v1.ConfigureRequest\x1a\x1f.levis.plugin.v1.ConfigureReply\x12F\n" +
	"\x06Health\x12\x1e.levis.plugin.v1.HealthRequest\x1a\x1c.levis.plugin.v1.HealthReply\x12L\n" +
	"\bShutdown\x12 .levis.plugin.v1.ShutdownRequest\x1a\x1e.levis.plugin.v1.ShutdownReply\x12L\n" +
	"\bSendMail\x12 .levis.plugin.v1.SendMailRequest\x1a\x1e.levis.plugin.v1.SendMailReply\x12[\n" +
	"\rCreatePayment\x12%.levis.plugin.v1.CreatePaymentRequest\x1a#.levis.plugin.v1.CreatePaymentReply\x12X\n" +
	"\fQueryPayment\x12$.levis.plugin.v1.QueryPaymentRequest\x1a\".levis.plugin.v1.QueryPaymentReply\x12s\n" +
	"\x15VerifyPaymentCallback\x12-.levis.plugin.v1.VerifyPaymentCallbackRequest\x1a+.levis.plugin.v1.VerifyPaymentCallbackReply\x12X\n" +
	"\fListProducts\x12$.levis.plugin.v1.ListProductsRequest\x1a\".levis.plugin.v1.ListProductsReply\x12R\n" +
	"\n" +
	"GetProduct\x12\".levis.plugin.v1.GetProductRequest\x1a .levis.plugin.v1.GetProductReply\x12U\n" +
	"\vCreateOrder\x12#.levis.plugin.v1.CreateOrderRequest\x1a!.levis.plugin.v1.CreateOrderReply\x12L\n" +
	"\bGetOrder\x12 .levis.plugin.v1.GetOrderRequest\x1a\x1e.levis.plugin.v1.GetOrderReply\x12R\n" +
	"\n" +
	"ManageHost\x12\".levis.plugin.v1.ManageHostRequest\x1a .levis.plugin.v1.ManageHostReply\x12I\n" +
	"\aGetHost\x12\x1f.levis.plugin.v1.GetHostRequest\x1a\x1d.levis.plugin.v1.GetHostReply\x12R\n" +
	"\n" +
	"ListHostOS\x12\".levis.plugin.v1.ListHostOSRequest\x1a .levis.plugin.v1.ListHostOSReply\x12L\n" +
	"\bStartKYC\x12 .levis.plugin.v1.StartKYCRequest\x1a\x1e.levis.plugin.v1.StartKYCReply\x12L\n" +
	"\bQueryKYC\x12 .levis.plugin.v1.QueryKYCRequest\x1a\x1e.levis.plugin.v1.QueryKYCReplyB:Z8github.com/SakuraOpenSource/levis/pkg/plugin/proto;protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 48)
var file_plugin_proto_goTypes = []any{
	(Capability)(0),                      // 0: levis.plugin.v1.Capability
	(FieldType)(0),                       // 1: levis.plugin.v1.FieldType
	(PaymentState)(0),                    // 2: levis.plugin.v1.PaymentState
	(HostAction)(0),                      // 3: levis.plugin.v1.HostAction
	(*ConfigField)(nil),                  // 4: levis.plugin.v1.ConfigField
	(*SelectOption)(nil),                 // 5: levis.plugin.v1.SelectOption
	(*DescribeRequest)(nil),              // 6: levis.plugin.v1.DescribeRequest
	(*Manifest)(nil),                     // 7: levis.plugin.v1.Manifest
	(*ConfigureRequest)(nil),             // 8: levis.plugin.v1.ConfigureRequest
	(*ConfigureReply)(nil),               // 9: levis.plugin.v1.ConfigureReply
	(*HealthRequest)(nil),                // 10: levis.plugin.v1.HealthRequest
	(*HealthReply)(nil),                  // 11: levis.plugin.v1.HealthReply
	(*ShutdownRequest)(nil),              // 12: levis.plugin.v1.ShutdownRequest
	(*ShutdownReply)(nil),                // 13: levis.plugin.v1.ShutdownReply
	(*Mailbox)(nil),                      // 14: levis.plugin.v1.Mailbox
	(*SendMailRequest)(nil),              // 15: levis.plugin.v1.SendMailRequest
	(*SendMailReply)(nil),                // 16: levis.plugin.v1.SendMailReply
	(*CreatePaymentRequest)(nil),         // 17: levis.plugin.v1.CreatePaymentRequest
	(*CreatePaymentReply)(nil),           // 18: levis.plugin.v1.CreatePaymentReply
	(*QueryPaymentRequest)(nil),          // 19: levis.plugin.v1.QueryPaymentRequest
	(*QueryPaymentReply)(nil),            // 20: levis.plugin.v1.QueryPaymentReply
	(*VerifyPaymentCallbackRequest)(nil), // 21: levis.plugin.v1.VerifyPaymentCallbackRequest
	(*VerifyPaymentCallbackReply)(nil),   // 22: levis.plugin.v1.VerifyPaymentCallbackReply
	(*ListProductsRequest)(nil),          // 23: levis.plugin.v1.ListProductsRequest
	(*UpstreamProduct)(nil),              // 24: levis.plugin.v1.UpstreamProduct
	(*ListProductsReply)(nil),            // 25: levis.plugin.v1.ListProductsReply
	(*GetProductRequest)(nil),            // 26: levis.plugin.v1.GetProductRequest
	(*GetProductReply)(nil),              // 27: levis.plugin.v1.GetProductReply
	(*CreateOrderRequest)(nil),           // 28: levis.plugin.v1.CreateOrderRequest
	(*CreateOrderReply)(nil),             // 29: levis.plugin.v1.CreateOrderReply
	(*GetOrderRequest)(nil),              // 30: levis.plugin.v1.GetOrderRequest
	(*GetOrderReply)(nil),                // 31: levis.plugin.v1.GetOrderReply
	(*ManageHostRequest)(nil),            // 32: levis.plugin.v1.ManageHostRequest
	(*ManageHostReply)(nil),              // 33: levis.plugin.v1.ManageHostReply
	(*GetHostRequest)(nil),               // 34: levis.plugin.v1.GetHostRequest
	(*UpstreamHost)(nil),                 // 35: levis.plugin.v1.UpstreamHost
	(*GetHostReply)(nil),                 // 36: levis.plugin.v1.GetHostReply
	(*OSImage)(nil),                      // 37: levis.plugin.v1.OSImage
	(*ListHostOSRequest)(nil),            // 38: levis.plugin.v1.ListHostOSRequest
	(*ListHostOSReply)(nil),              // 39: levis.plugin.v1.ListHostOSReply
	(*StartKYCRequest)(nil),              // 40: levis.plugin.v1.StartKYCRequest
	(*StartKYCReply)(nil),                // 41: levis.plugin.v1.StartKYCReply
	(*QueryKYCRequest)(nil),              // 42: levis.plugin.v1.QueryKYCRequest
	(*QueryKYCReply)(nil),                // 43: levis.plugin.v1.QueryKYCReply
	nil,                                  // 44: levis.plugin.v1.ConfigureRequest.ValuesEntry
	nil,                                  // 45: levis.plugin.v1.CreatePaymentRequest.ConfigEntry
	nil,                                  // 46: levis.plugin.v1.QueryPaymentRequest.ConfigEntry
	nil,                                  // 47: levis.plugin.v1.VerifyPaymentCallbackRequest.RawEntry
	nil,                                  // 48: levis.plugin.v1.VerifyPaymentCallbackRequest.ConfigEntry
	nil,                                  // 49: levis.plugin.v1.UpstreamProduct.SpecsEntry
	nil,                                  // 50: levis.plugin.v1.StartKYCRequest.ConfigEntry
	nil,                                  // 51: levis.plugin.v1.QueryKYCRequest.ConfigEntry
}
var file_plugin_proto_depIdxs = []int32{
	1,  // 0: levis.plugin.v1.ConfigField.type:type_name -> levis.plugin.v1.FieldType
	5,  // 1: levis.plugin.v1.ConfigField.options:type_name -> levis.plugin.v1.SelectOption
	0,  // 2: levis.plugin.v1.Manifest.capabilities:type_name -> levis.plugin.v1.Capability
	4,  // 3: levis.plugin.v1.Manifest.config:type_name -> levis.plugin.v1.ConfigField
	4,  // 4: levis.plugin.v1.Manifest.payment_config:type_name -> levis.plugin.v1.ConfigField
	44, // 5: levis.plugin.v1.ConfigureRequest.values:type_name -> levis.plugin.v1.ConfigureRequest.ValuesEntry
	14, // 6: levis.plugin.v1.SendMailRequest.to:type_name -> levis.plugin.v1.Mailbox
	45, // 7: levis.plugin.v1.CreatePaymentRequest.config:type_name -> levis.plugin.v1.CreatePaymentRequest.ConfigEntry
	46, // 8: levis.plugin.v1.QueryPaymentRequest.config:type_name -> levis.plugin.v1.QueryPaymentRequest.ConfigEntry
	2,  // 9: levis.plugin.v1.QueryPaymentReply.state:type_name -> levis.plugin.v1.PaymentState
	47, // 10: levis.plugin.v1.VerifyPaymentCallbackRequest.raw:type_name -> levis.plugin.v1.VerifyPaymentCallbackRequest.RawEntry
	48, // 11: levis.plugin.v1.VerifyPaymentCallbackRequest.config:type_name -> levis.plugin.v1.VerifyPaymentCallbackRequest.ConfigEntry
	2,  // 12: levis.plugin.v1.VerifyPaymentCallbackReply.state:type_name -> levis.plugin.v1.PaymentState
	49, // 13: levis.plugin.v1.UpstreamProduct.specs:type_name -> levis.plugin.v1.UpstreamProduct.SpecsEntry
	24, // 14: levis.plugin.v1.ListProductsReply.products:type_name -> levis.plugin.v1.UpstreamProduct
	24, // 15: levis.plugin.v1.GetProductReply.product:type_name -> levis.plugin.v1.UpstreamProduct
	3,  // 16: levis.plugin.v1.ManageHostRequest.action:type_name -> levis.plugin.v1.HostAction
	35, // 17: levis.plugin.v1.GetHostReply.host:type_name -> levis.plugin.v1.UpstreamHost
	37, // 18: levis.plugin.v1.ListHostOSReply.os:type_name -> levis.plugin.v1.OSImage
	50, // 19: levis.plugin.v1.StartKYCRequest.config:type_name -> levis.plugin.v1.StartKYCRequest.ConfigEntry
	51, // 20: levis.plugin.v1.QueryKYCRequest.config:type_name -> levis.plugin.v1.QueryKYCRequest.ConfigEntry
	6,  // 21: levis.plugin.v1.Plugin.Describe:input_type -> levis.plugin.v1.DescribeRequest
	8,  // 22: levis.plugin.v1.Plugin.Configure:input_type -> levis.plugin.v1.ConfigureRequest
	10, // 23: levis.plugin.v1.Plugin.Health:input_type -> levis.plugin.v1.HealthRequest
	12, // 24: levis.plugin.v1.Plugin.Shutdown:input_type -> levis.plugin.v1.ShutdownRequest
	15, // 25: levis.plugin.v1.Plugin.SendMail:input_type -> levis.plugin.v1.SendMailRequest
	17, // 26: levis.plugin.v1.Plugin.CreatePayment:input_type -> levis.plugin.v1.CreatePaymentRequest
	19, // 27: levis.plugin.v1.Plugin.QueryPayment:input_type -> levis.plugin.v1.QueryPaymentRequest
	21, // 28: levis.plugin.v1.Plugin.VerifyPaymentCallback:input_type -> levis.plugin.v1.VerifyPaymentCallbackRequest
	23, // 29: levis.plugin.v1.Plugin.ListProducts:input_type -> levis.plugin.v1.ListProductsRequest
	26, // 30: levis.plugin.v1.Plugin.GetProduct:input_type -> levis.plugin.v1.GetProductRequest
	28, // 31: levis.plugin.v1.Plugin.CreateOrder:input_type -> levis.plugin.v1.CreateOrderRequest
	30, // 32: levis.plugin.v1.Plugin.GetOrder:input_type -> levis.plugin.v1.GetOrderRequest
	32, // 33: levis.plugin.v1.Plugin.ManageHost:input_type -> levis.plugin.v1.ManageHostRequest
	34, // 34: levis.plugin.v1.Plugin.GetHost:input_type -> levis.plugin.v1.GetHostRequest
	38, // 35: levis.plugin.v1.Plugin.ListHostOS:input_type -> levis.plugin.v1.ListHostOSRequest
	40, // 36: levis.plugin.v1.Plugin.StartKYC:input_type -> levis.plugin.v1.StartKYCRequest
	42, // 37: levis.plugin.v1.Plugin.QueryKYC:input_type -> levis.plugin.v1.QueryKYCRequest
	7,  // 38: levis.plugin.v1.Plugin.Describe:output_type -> levis.plugin.v1.Manifest
	9,  // 39: levis.plugin.v1.Plugin.Configure:output_type -> levis.plugin.v1.ConfigureReply
	11, // 40: levis.plugin.v1.Plugin.Health:output_type -> levis.plugin.v1.HealthReply
	13, // 41: levis.plugin.v1.Plugin.Shutdown:output_type -> levis.plugin.v1.ShutdownReply
	16, // 42: levis.plugin.v1.Plugin.SendMail:output_type -> levis.plugin.v1.SendMailReply
	18, // 43: levis.plugin.v1.Plugin.CreatePayment:output_type -> levis.plugin.v1.CreatePaymentReply
	20, // 44: levis.plugin.v1.Plugin.QueryPayment:output_type -> levis.plugin.v1.QueryPaymentReply
	22, // 45: levis.plugin.v1.Plugin.VerifyPaymentCallback:output_type -> levis.plugin.v1.VerifyPaymentCallbackReply
	25, // 46: levis.plugin.v1.Plugin.ListProducts:output_type -> levis.plugin.v1.ListProductsReply
	27, // 47: levis.plugin.v1.Plugin.GetProduct:output_type -> levis.plugin.v1.GetProductReply
	29, // 48: levis.plugin.v1.Plugin.CreateOrder:output_type -> levis.plugin.v1.CreateOrderReply
	31, // 49: levis.plugin.v1.Plugin.GetOrder:output_type -> levis.plugin.v1.GetOrderReply
	33, // 50: levis.plugin.v1.Plugin.ManageHost:output_type -> levis.plugin.v1.ManageHostReply
	36, // 51: levis.plugin.v1.Plugin.GetHost:output_type -> levis.plugin.v1.GetHostReply
	39, // 52: levis.plugin.v1.Plugin.ListHostOS:output_type -> levis.plugin.v1.ListHostOSReply
	41, // 53: levis.plugin.v1.Plugin.StartKYC:output_type -> levis.plugin.v1.StartKYCReply
	43, // 54: levis.plugin.v1.Plugin.QueryKYC:output_type -> levis.plugin.v1.QueryKYCReply
	38, // [38:55] is the sub-list for method output_type
	21, // [21:38] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   48,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
