// Levis 插件契约。
//
// 插件是独立的可执行程序，与主程序通过本文件定义的 gRPC 服务通信。
// 主程序始终是客户端，插件是服务端 —— 插件若要读写 Levis 的数据，
// 走 HTTP 回调 /api/plugin/v1，不在本契约内。
//
// 兼容性约定：字段只增不改，废弃字段用 reserved 占位，绝不复用编号。
// 插件与主程序的版本可能不一致，改动必须让旧插件仍能工作。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Plugin_Describe_FullMethodName              = "/levis.plugin.v1.Plugin/Describe"
	Plugin_Configure_FullMethodName             = "/levis.plugin.v1.Plugin/Configure"
	Plugin_Health_FullMethodName                = "/levis.plugin.v1.Plugin/Health"
	Plugin_Shutdown_FullMethodName              = "/levis.plugin.v1.Plugin/Shutdown"
	Plugin_SendMail_FullMethodName              = "/levis.plugin.v1.Plugin/SendMail"
	Plugin_CreatePayment_FullMethodName         = "/levis.plugin.v1.Plugin/CreatePayment"
	Plugin_QueryPayment_FullMethodName          = "/levis.plugin.v1.Plugin/QueryPayment"
	Plugin_VerifyPaymentCallback_FullMethodName = "/levis.plugin.v1.Plugin/VerifyPaymentCallback"
	Plugin_ListProducts_FullMethodName          = "/levis.plugin.v1.Plugin/ListProducts"
	Plugin_GetProduct_FullMethodName            = "/levis.plugin.v1.Plugin/GetProduct"
	Plugin_CreateOrder_FullMethodName           = "/levis.plugin.v1.Plugin/CreateOrder"
	Plugin_GetOrder_FullMethodName              = "/levis.plugin.v1.Plugin/GetOrder"
	Plugin_ManageHost_FullMethodName            = "/levis.plugin.v1.Plugin/ManageHost"
	Plugin_GetHost_FullMethodName               = "/levis.plugin.v1.Plugin/GetHost"
	Plugin_ListHostOS_FullMethodName            = "/levis.plugin.v1.Plugin/ListHostOS"
	Plugin_ListProductOS_FullMethodName         = "/levis.plugin.v1.Plugin/ListProductOS"
	Plugin_StartKYC_FullMethodName              = "/levis.plugin.v1.Plugin/StartKYC"
	Plugin_QueryKYC_FullMethodName              = "/levis.plugin.v1.Plugin/QueryKYC"
)

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Plugin 是每个插件都必须实现的服务。
//
// 生命周期方法（Describe/Configure/Health/Shutdown）是必须实现的；能力方法
// 按 Manifest 里声明的 capabilities 实现，未声明的直接返回 UNIMPLEMENTED，
// 主程序不会去调。
type PluginClient interface {
	// Describe 返回插件的身份与能力。主程序在握手后立刻调用。
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*Manifest, error)
	// Configure 下发管理员在后台填写的配置。
	//
	// 每次配置变更后都会重新调用，插件应当能够重复接收 —— 比如把 SMTP
	// 连接池按新参数重建，而不是只在第一次生效。
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureReply, error)
	// Health 用于存活探测，主程序按固定间隔调用。
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error)
	// Shutdown 通知插件即将退出，插件应当收尾并尽快返回。
	//
	// 返回后主程序仍会等待进程自行退出，超时才发信号。
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error)
	// SendMail 发送一封邮件。需声明 CAPABILITY_SEND_MAIL。
	SendMail(ctx context.Context, in *SendMailRequest, opts ...grpc.CallOption) (*SendMailReply, error)
	// CreatePayment 创建一笔支付，返回可供用户跳转的地址。
	// 需声明 CAPABILITY_CREATE_PAYMENT。
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentReply, error)
	// QueryPayment 查询一笔支付的当前状态，用于用户回到站点后主动核对，
	// 不依赖渠道回调是否已经到达。需声明 CAPABILITY_CREATE_PAYMENT。
	QueryPayment(ctx context.Context, in *QueryPaymentRequest, opts ...grpc.CallOption) (*QueryPaymentReply, error)
	// VerifyPaymentCallback 验证并归一化支付渠道的异步通知。
	// 主程序只把渠道原始字段交给插件，不信任其中的用户、金额或支付状态；
	// 插件验签后返回商户单号与实收金额，再由主程序匹配本地支付意图。
	// 需声明 CAPABILITY_CREATE_PAYMENT。
	VerifyPaymentCallback(ctx context.Context, in *VerifyPaymentCallbackRequest, opts ...grpc.CallOption) (*VerifyPaymentCallbackReply, error)
	// ListProducts 拉取上游供货商的产品列表。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsReply, error)
	// GetProduct 获取单个产品的详细信息。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductReply, error)
	// CreateOrder 在上游创建订单，返回上游订单号。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error)
	// GetOrder 查询上游订单状态。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderReply, error)
	// ManageHost 管理上游服务实例（续费/暂停/解除暂停/删除）。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	ManageHost(ctx context.Context, in *ManageHostRequest, opts ...grpc.CallOption) (*ManageHostReply, error)
	// GetHost 查询上游服务实例详情。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*GetHostReply, error)
	// ListHostOS 获取重装系统可选列表。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	ListHostOS(ctx context.Context, in *ListHostOSRequest, opts ...grpc.CallOption) (*ListHostOSReply, error)
	// ListProductOS 获取商品在购买时可选的系统镜像列表。
	// 与 ListHostOS（重装已有主机）相对：本方法面向开通前的选型，
	// 供购买页渲染系统下拉。未实现的插件返回 UNIMPLEMENTED，主程序须容忍。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	ListProductOS(ctx context.Context, in *ListProductOSRequest, opts ...grpc.CallOption) (*ListHostOSReply, error)
	// StartKYC 发起实名认证并返回认证跳转地址/HTML。
	// 需声明 CAPABILITY_KYC。
	StartKYC(ctx context.Context, in *StartKYCRequest, opts ...grpc.CallOption) (*StartKYCReply, error)
	// QueryKYC 查询实名认证结果。
	// 需声明 CAPABILITY_KYC。
	QueryKYC(ctx context.Context, in *QueryKYCRequest, opts ...grpc.CallOption) (*QueryKYCReply, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*Manifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Manifest)
	err := c.cc.Invoke(ctx, Plugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureReply)
	err := c.cc.Invoke(ctx, Plugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, Plugin_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownReply)
	err := c.cc.Invoke(ctx, Plugin_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) SendMail(ctx context.Context, in *SendMailRequest, opts ...grpc.CallOption) (*SendMailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMailReply)
	err := c.cc.Invoke(ctx, Plugin_SendMail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentReply)
	err := c.cc.Invoke(ctx, Plugin_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) QueryPayment(ctx context.Context, in *QueryPaymentRequest, opts ...grpc.CallOption) (*QueryPaymentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPaymentReply)
	err := c.cc.Invoke(ctx, Plugin_QueryPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) VerifyPaymentCallback(ctx context.Context, in *VerifyPaymentCallbackRequest, opts ...grpc.CallOption) (*VerifyPaymentCallbackReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPaymentCallbackReply)
	err := c.cc.Invoke(ctx, Plugin_VerifyPaymentCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsReply)
	err := c.cc.Invoke(ctx, Plugin_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductReply)
	err := c.cc.Invoke(ctx, Plugin_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderReply)
	err := c.cc.Invoke(ctx, Plugin_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderReply)
	err := c.cc.Invoke(ctx, Plugin_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) ManageHost(ctx context.Context, in *ManageHostRequest, opts ...grpc.CallOption) (*ManageHostReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManageHostReply)
	err := c.cc.Invoke(ctx, Plugin_ManageHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*GetHostReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostReply)
	err := c.cc.Invoke(ctx, Plugin_GetHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) ListHostOS(ctx context.Context, in *ListHostOSRequest, opts ...grpc.CallOption) (*ListHostOSReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHostOSReply)
	err := c.cc.Invoke(ctx, Plugin_ListHostOS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) ListProductOS(ctx context.Context, in *ListProductOSRequest, opts ...grpc.CallOption) (*ListHostOSReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHostOSReply)
	err := c.cc.Invoke(ctx, Plugin_ListProductOS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) StartKYC(ctx context.Context, in *StartKYCRequest, opts ...grpc.CallOption) (*StartKYCReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartKYCReply)
	err := c.cc.Invoke(ctx, Plugin_StartKYC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) QueryKYC(ctx context.Context, in *QueryKYCRequest, opts ...grpc.CallOption) (*QueryKYCReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryKYCReply)
	err := c.cc.Invoke(ctx, Plugin_QueryKYC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility.
//
// Plugin 是每个插件都必须实现的服务。
//
// 生命周期方法（Describe/Configure/Health/Shutdown）是必须实现的；能力方法
// 按 Manifest 里声明的 capabilities 实现，未声明的直接返回 UNIMPLEMENTED，
// 主程序不会去调。
type PluginServer interface {
	// Describe 返回插件的身份与能力。主程序在握手后立刻调用。
	Describe(context.Context, *DescribeRequest) (*Manifest, error)
	// Configure 下发管理员在后台填写的配置。
	//
	// 每次配置变更后都会重新调用，插件应当能够重复接收 —— 比如把 SMTP
	// 连接池按新参数重建，而不是只在第一次生效。
	Configure(context.Context, *ConfigureRequest) (*ConfigureReply, error)
	// Health 用于存活探测，主程序按固定间隔调用。
	Health(context.Context, *HealthRequest) (*HealthReply, error)
	// Shutdown 通知插件即将退出，插件应当收尾并尽快返回。
	//
	// 返回后主程序仍会等待进程自行退出，超时才发信号。
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownReply, error)
	// SendMail 发送一封邮件。需声明 CAPABILITY_SEND_MAIL。
	SendMail(context.Context, *SendMailRequest) (*SendMailReply, error)
	// CreatePayment 创建一笔支付，返回可供用户跳转的地址。
	// 需声明 CAPABILITY_CREATE_PAYMENT。
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentReply, error)
	// QueryPayment 查询一笔支付的当前状态，用于用户回到站点后主动核对，
	// 不依赖渠道回调是否已经到达。需声明 CAPABILITY_CREATE_PAYMENT。
	QueryPayment(context.Context, *QueryPaymentRequest) (*QueryPaymentReply, error)
	// VerifyPaymentCallback 验证并归一化支付渠道的异步通知。
	// 主程序只把渠道原始字段交给插件，不信任其中的用户、金额或支付状态；
	// 插件验签后返回商户单号与实收金额，再由主程序匹配本地支付意图。
	// 需声明 CAPABILITY_CREATE_PAYMENT。
	VerifyPaymentCallback(context.Context, *VerifyPaymentCallbackRequest) (*VerifyPaymentCallbackReply, error)
	// ListProducts 拉取上游供货商的产品列表。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsReply, error)
	// GetProduct 获取单个产品的详细信息。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	GetProduct(context.Context, *GetProductRequest) (*GetProductReply, error)
	// CreateOrder 在上游创建订单，返回上游订单号。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderReply, error)
	// GetOrder 查询上游订单状态。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderReply, error)
	// ManageHost 管理上游服务实例（续费/暂停/解除暂停/删除）。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	ManageHost(context.Context, *ManageHostRequest) (*ManageHostReply, error)
	// GetHost 查询上游服务实例详情。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	GetHost(context.Context, *GetHostRequest) (*GetHostReply, error)
	// ListHostOS 获取重装系统可选列表。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	ListHostOS(context.Context, *ListHostOSRequest) (*ListHostOSReply, error)
	// ListProductOS 获取商品在购买时可选的系统镜像列表。
	// 与 ListHostOS（重装已有主机）相对：本方法面向开通前的选型，
	// 供购买页渲染系统下拉。未实现的插件返回 UNIMPLEMENTED，主程序须容忍。
	// 需声明 CAPABILITY_PROVISION_PRODUCT。
	ListProductOS(context.Context, *ListProductOSRequest) (*ListHostOSReply, error)
	// StartKYC 发起实名认证并返回认证跳转地址/HTML。
	// 需声明 CAPABILITY_KYC。
	StartKYC(context.Context, *StartKYCRequest) (*StartKYCReply, error)
	// QueryKYC 查询实名认证结果。
	// 需声明 CAPABILITY_KYC。
	QueryKYC(context.Context, *QueryKYCRequest) (*QueryKYCReply, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServer struct{}

func (UnimplementedPluginServer) Describe(context.Context, *DescribeRequest) (*Manifest, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedPluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedPluginServer) Health(context.Context, *HealthRequest) (*HealthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPluginServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPluginServer) SendMail(context.Context, *SendMailRequest) (*SendMailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMail not implemented")
}
func (UnimplementedPluginServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPluginServer) QueryPayment(context.Context, *QueryPaymentRequest) (*QueryPaymentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryPayment not implemented")
}
func (UnimplementedPluginServer) VerifyPaymentCallback(context.Context, *VerifyPaymentCallbackRequest) (*VerifyPaymentCallbackReply, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPaymentCallback not implemented")
}
func (UnimplementedPluginServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedPluginServer) GetProduct(context.Context, *GetProductRequest) (*GetProductReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedPluginServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedPluginServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedPluginServer) ManageHost(context.Context, *ManageHostRequest) (*ManageHostReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ManageHost not implemented")
}
func (UnimplementedPluginServer) GetHost(context.Context, *GetHostRequest) (*GetHostReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHost not implemented")
}
func (UnimplementedPluginServer) ListHostOS(context.Context, *ListHostOSRequest) (*ListHostOSReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHostOS not implemented")
}
func (UnimplementedPluginServer) ListProductOS(context.Context, *ListProductOSRequest) (*ListHostOSReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductOS not implemented")
}
func (UnimplementedPluginServer) StartKYC(context.Context, *StartKYCRequest) (*StartKYCReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StartKYC not implemented")
}
func (UnimplementedPluginServer) QueryKYC(context.Context, *QueryKYCRequest) (*QueryKYCReply, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryKYC not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}
func (UnimplementedPluginServer) testEmbeddedByValue()                {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	// If the following call panics, it indicates UnimplementedPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).SendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_SendMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).SendMail(ctx, req.(*SendMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_QueryPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).QueryPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_QueryPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).QueryPayment(ctx, req.(*QueryPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_VerifyPaymentCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPaymentCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).VerifyPaymentCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_VerifyPaymentCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).VerifyPaymentCallback(ctx, req.(*VerifyPaymentCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_ManageHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ManageHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_ManageHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ManageHost(ctx, req.(*ManageHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_GetHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_GetHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetHost(ctx, req.(*GetHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_ListHostOS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostOSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ListHostOS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_ListHostOS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ListHostOS(ctx, req.(*ListHostOSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_ListProductOS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductOSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ListProductOS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_ListProductOS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ListProductOS(ctx, req.(*ListProductOSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_StartKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).StartKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_StartKYC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).StartKYC(ctx, req.(*StartKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_QueryKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).QueryKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_QueryKYC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).QueryKYC(ctx, req.(*QueryKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "levis.plugin.v1.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Plugin_Describe_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Plugin_Configure_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Plugin_Health_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Plugin_Shutdown_Handler,
		},
		{
			MethodName: "SendMail",
			Handler:    _Plugin_SendMail_Handler,
		},
		{
			MethodName: "CreatePayment",
			Handler:    _Plugin_CreatePayment_Handler,
		},
		{
			MethodName: "QueryPayment",
			Handler:    _Plugin_QueryPayment_Handler,
		},
		{
			MethodName: "VerifyPaymentCallback",
			Handler:    _Plugin_VerifyPaymentCallback_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _Plugin_ListProducts_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _Plugin_GetProduct_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Plugin_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _Plugin_GetOrder_Handler,
		},
		{
			MethodName: "ManageHost",
			Handler:    _Plugin_ManageHost_Handler,
		},
		{
			MethodName: "GetHost",
			Handler:    _Plugin_GetHost_Handler,
		},
		{
			MethodName: "ListHostOS",
			Handler:    _Plugin_ListHostOS_Handler,
		},
		{
			MethodName: "ListProductOS",
			Handler:    _Plugin_ListProductOS_Handler,
		},
		{
			MethodName: "StartKYC",
			Handler:    _Plugin_StartKYC_Handler,
		},
		{
			MethodName: "QueryKYC",
			Handler:    _Plugin_QueryKYC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
